import type { AssuranceRule } from "@/lib/types/rule";

// Layer 3 — AP Intelligence Engine: 40 rules
// Purpose: Are liabilities complete and payments controlled?

const apIntelligenceRulesRaw: AssuranceRule[] = [
  { id: "AP_001", layer: 3, name: "DUPLICATE_INVOICE_REFERENCE", fileType: "aged_creditors", category: "ap", severity: "high", confidence: "high", type: "ledger_metric", ledgerMetric: "duplicate_reference", field: ["invoice_ref","reference"], nameField: ["supplier","vendor"], message: "Duplicate invoice references in AP — verify before payment", description: "Duplicate invoice references are the leading cause of duplicate payments in AP ledgers.", detail: "The same supplier/reference combination appears more than once.", impact: "Duplicate payment risk", recommendation: "Investigate all duplicate invoice references — hold second payment pending supplier confirmation.", evidenceStrength: "deterministic" },
  { id: "AP_002", layer: 3, name: "NEGATIVE_SUPPLIER_BALANCE", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "high", type: "sign", field: ["balance","amount","outstanding"], keywords: ["negative"], nameField: ["supplier","vendor"], message: "{{count}} suppliers have negative balances (debit) — {{total}} overpaid", description: "Debit balances on creditor accounts indicate overpayment — money is owed back by the supplier.", detail: "{{count}} creditors with debit balances totalling {{total}}: {{names}}", impact: "{{total}} recovery opportunity from overpaid suppliers", recommendation: "Contact suppliers with debit balances — arrange refund or credit against next invoice." },
  { id: "AP_003", layer: 3, name: "OLD_UNCLEARED_INVOICE_90_DAYS", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: 90, nameField: ["supplier","vendor"], message: "{{count}} AP invoices uncleared for 90+ days — {{total}}", description: "Creditor items outstanding over 90 days may indicate payment disputes or lost invoices.", detail: "{{count}} invoices aged 90+ days totalling {{total}}.", impact: "Supplier relationship and cash flow risk", recommendation: "Reconcile old AP items — clear, dispute or write back stale balances." },
  { id: "AP_004", layer: 3, name: "OLD_UNCLEARED_INVOICE_180_DAYS", fileType: "aged_creditors", category: "ap", severity: "high", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: 180, nameField: ["supplier","vendor"], message: "{{count}} AP invoices uncleared for 180+ days — {{total}}", description: "Invoices outstanding for over 180 days may represent disputed items, ghost invoices or payment failures.", detail: "{{count}} AP items aged 180+ days: {{names}}", impact: "Supplier relationship risk and potential legal action", recommendation: "Escalate all 180+ day AP items — seek formal resolution with suppliers." },
  { id: "AP_005", layer: 3, name: "OLD_UNCLEARED_INVOICE_365_DAYS", fileType: "aged_creditors", category: "ap", severity: "critical", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: 365, nameField: ["supplier","vendor"], message: "{{count}} AP invoices over 1 year old — {{total}} — write-back review", description: "AP balances over 12 months old may represent unclaimed balances or errors that should be written back.", detail: "{{count}} AP items aged 365+ days totalling {{total}}.", impact: "{{total}} — may be eligible for write-back", recommendation: "Review legal position on aged creditors — consider writing back balances over 12 months where supplier cannot be traced." },
  { id: "AP_006", layer: 3, name: "PERSONAL_PAYEE_DETECTED", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "pattern", field: ["supplier","vendor"], pattern: "^(Mr|Mrs|Ms|Miss|Dr|Prof)\\.?\\s+[A-Za-z]+|^[A-Z][a-z]+ [A-Z][a-z]+$", nameField: ["supplier","vendor"], message: "{{count}} payments to individual persons — IR35 or fraud risk", description: "Payments to individuals may have PAYE/IR35 implications and require additional due diligence.", detail: "{{count}} payees appear to be individuals rather than companies.", impact: "IR35, PAYE and fraud risk", recommendation: "Confirm IR35 status for individual payees — ensure proper PAYE compliance and obtain management approval." },
  { id: "AP_007", layer: 3, name: "SUPPLIER_CONCENTRATION_RISK", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "high", type: "ledger_metric", ledgerMetric: "single_party_concentration", threshold: 0.3, nameField: ["supplier","vendor"], message: "Supplier concentration risk — one supplier exceeds 30% of AP", description: "Heavy reliance on a single supplier creates concentration and supply chain risk.", detail: "A single supplier accounts for more than 30% of total AP outstanding.", impact: "Supplier concentration and supply chain risk", recommendation: "Diversify supplier base — avoid single-source dependency for critical supplies.", evidenceStrength: "deterministic" },
  { id: "AP_008", layer: 3, name: "NEW_VENDOR_LARGE_INVOICE", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "medium", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 5000, nameField: ["supplier","vendor"], message: "{{count}} first-time vendors with invoices over £5,000", description: "New vendors with high-value first invoices require enhanced due diligence and approval.", detail: "{{count}} vendors appear as first-time payees with balances over £5,000.", impact: "Vendor fraud risk on first-time payments", recommendation: "Perform vendor due diligence — verify bank details, company registration and obtain management sign-off." },
  { id: "AP_009", layer: 3, name: "ROUND_NUMBER_INVOICE_SPIKE", fileType: "aged_creditors", category: "controls", severity: "low", confidence: "low", type: "percentage", field: ["amount","balance"], keywords: [], percentage: 20, message: "High proportion of round-number invoices in AP (>20%)", description: "A high proportion of round-number amounts may indicate estimated rather than actual invoiced amounts.", detail: "Over 20% of AP invoices are exact multiples of £1,000.", impact: "Estimation risk — confirm amounts are actual", recommendation: "Verify that round-number AP invoices represent actual supplier invoices.", evidenceStrength: "indicator" },
  { id: "AP_010", layer: 3, name: "INTERCOMPANY_AP_OUTSTANDING", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["supplier","vendor"], keywords: ["intercompany","intra-group","related party","group company","sister","subsidiary","parent"], nameField: ["supplier","vendor"], message: "{{count}} intercompany payables outstanding — {{total}}", description: "Intercompany AP balances must be confirmed with the counterpart and eliminated in consolidation.", detail: "{{count}} intercompany creditor balances identified: {{names}}", impact: "Consolidation elimination required", recommendation: "Confirm intercompany payables with counterpart entities — eliminate on consolidation." },
  { id: "AP_011", layer: 3, name: "CRITICAL_SUPPLIER_ON_HOLD", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "high", type: "keyword", field: ["status","supplier"], keywords: ["stop","hold","blocked","suspended","dispute","hold payment"], nameField: ["supplier","vendor"], message: "{{count}} suppliers on payment hold — {{total}}", description: "Suppliers on payment hold may indicate disputes — ensure holds are properly authorised.", detail: "{{count}} suppliers have payment hold status: {{names}}", impact: "Supplier relationship and supply chain risk", recommendation: "Review payment holds — confirm authorisation and resolve underlying disputes." },
  { id: "AP_012", layer: 3, name: "RETENTIONS_DUE_FOR_RELEASE", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "medium", type: "keyword", field: ["description","account_name"], keywords: ["retention","retainer","defect liability","hold-back"], nameField: ["supplier","vendor"], message: "{{count}} supplier retention amounts — {{total}} review for release", description: "Contractor retention amounts may be due for release following completion of defect liability periods.", detail: "{{count}} retention/defect liability amounts identified: {{total}}", impact: "{{total}} — review release date and conditions", recommendation: "Review contract terms for retention release — schedule payment for amounts now due." },
  { id: "AP_013", layer: 3, name: "PREPAYMENT_SUPPLIERS_LARGE", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "medium", type: "keyword", field: ["description","invoice_ref"], keywords: ["prepay","advance","deposit","upfront","stage payment","down payment"], nameField: ["supplier","vendor"], message: "{{count}} large supplier prepayments or deposits — {{total}}", description: "Prepayments to suppliers carry counterparty risk if the supplier fails to deliver.", detail: "{{count}} prepayment or deposit items totalling {{total}}.", impact: "Counterparty risk on advance payments", recommendation: "Confirm prepayment suppliers are financially sound — consider performance bonds for material advances." },
  { id: "AP_014", layer: 3, name: "AP_STATEMENT_RECONCILIATION_GAP", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "low", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 50000, nameField: ["supplier","vendor"], message: "{{count}} large supplier balances requiring statement reconciliation", description: "Large supplier balances should be reconciled to supplier statements before payment.", detail: "{{count}} suppliers with balances over £50,000: {{names}}", impact: "Payment error risk on large supplier balances", recommendation: "Request supplier statements for all balances over £50,000 — reconcile before making payment." },
  { id: "AP_015", layer: 3, name: "MISSING_ACCRUAL_UTILITIES", fileType: "aged_creditors", category: "month_end", severity: "low", confidence: "medium", type: "keyword", field: ["supplier","vendor"], keywords: ["utility","utilities","electricity","gas","water","electric","energy"], nameField: ["supplier","vendor"], message: "Review reminder: utility suppliers detected — confirm uninvoiced accruals", description: "Utility suppliers indicate a recurring cost category, but supplier presence alone is not an accrual exception.", detail: "Utility supplier(s) identified: {{names}}", impact: "Review reminder — recurring utility accrual may be needed", recommendation: "Check invoice timing and post utility accruals only where costs have been incurred but not invoiced.", evidenceStrength: "advisory" },
  { id: "AP_016", layer: 3, name: "MISSING_ACCRUAL_RENT", fileType: "aged_creditors", category: "month_end", severity: "low", confidence: "medium", type: "keyword", field: ["supplier","vendor"], keywords: ["rent","rates","lease","landlord","property"], nameField: ["supplier","vendor"], message: "Review reminder: rent/rates suppliers detected — confirm accruals", description: "Rent and property suppliers indicate a recurring cost category, but supplier presence alone is not a missing accrual.", detail: "Rent/rates supplier(s) identified: {{names}}", impact: "Review reminder — rent accrual may be needed", recommendation: "Review lease/rates invoice timing and post accruals only for uninvoiced period costs.", evidenceStrength: "advisory" },
  { id: "AP_017", layer: 3, name: "MISSING_ACCRUAL_PROFESSIONAL_FEES", fileType: "aged_creditors", category: "month_end", severity: "low", confidence: "medium", type: "keyword", field: ["supplier","vendor"], keywords: ["accountant","solicitor","legal","professional","audit","consultant"], nameField: ["supplier","vendor"], message: "Review reminder: professional fee suppliers detected", description: "Professional fee suppliers indicate a recurring cost category, but supplier presence alone is not an accrual exception.", detail: "Professional fee supplier(s) identified: {{names}}", impact: "Review reminder — professional fee accrual may be needed", recommendation: "Confirm fee invoice schedules and accrue only for services received but not invoiced.", evidenceStrength: "advisory" },
  { id: "AP_018", layer: 3, name: "SPLIT_INVOICE_PATTERN", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "medium", type: "threshold", field: ["amount","balance"], comparator: "lt", threshold: 1000, nameField: ["supplier","vendor"], message: "Possible approval limit avoidance — multiple small invoices from same supplier", description: "Multiple invoices from the same supplier, each below an approval threshold, may indicate deliberate splitting to avoid authorisation.", detail: "Multiple sub-£1,000 invoices from same supplier on similar dates detected.", impact: "Approval bypass risk — review authorisation controls", recommendation: "Review split invoice patterns — implement cumulative approval thresholds.", evidenceStrength: "indicator" },
  { id: "AP_019", layer: 3, name: "LARGE_INVOICE_NO_PO", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 10000, nameField: ["supplier","vendor"], message: "{{count}} large AP invoices (>£10,000) — confirm PO exists", description: "Large invoices without an associated purchase order may have bypassed normal approval controls.", detail: "{{count}} invoices over £10,000 found in AP: {{names}}", impact: "Purchase order and approval controls may be bypassed", recommendation: "Confirm all invoices over £10,000 have an associated approved purchase order." },
  { id: "AP_020", layer: 3, name: "VENDOR_BANK_CHANGE_RISK", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["description","memo","status"], keywords: ["bank change","new bank","updated bank","new account","payment details changed"], nameField: ["supplier","vendor"], message: "{{count}} suppliers with possible bank detail changes noted", description: "Fraudsters sometimes intercept supplier communications to redirect payments to their own bank accounts.", detail: "{{count}} supplier records show bank change indicators.", impact: "Invoice fraud risk — payment redirection", recommendation: "Call suppliers on known numbers to verify any bank detail changes before processing payment." },
  { id: "AP_021", layer: 3, name: "INSURANCE_ACCRUAL_MISSING", fileType: "aged_creditors", category: "month_end", severity: "low", confidence: "medium", type: "keyword", field: ["supplier","vendor"], keywords: ["insurance","indemnity","premium","policy"], nameField: ["supplier","vendor"], message: "Review reminder: insurance supplier detected", description: "Insurance premiums are normally annual or monthly, but supplier presence alone is not a missing accrual.", detail: "Insurance supplier(s) identified: {{names}}", impact: "Review reminder — insurance accrual may be required", recommendation: "Confirm insurance premium schedule and accrue only for uninvoiced cover period.", evidenceStrength: "advisory" },
  { id: "AP_022", layer: 3, name: "HIGH_VALUE_AP_PAYMENT_CONCENTRATION", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "medium", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 250000, nameField: ["supplier","vendor"], message: "{{count}} suppliers with balances exceeding £250,000 — material concentration", description: "Very large individual supplier balances require specific payment risk assessment.", detail: "{{count}} suppliers with balances over £250,000: {{names}}", impact: "Material supplier payment risk", recommendation: "Obtain board approval for payments over £250,000 — ensure dual authorisation." },
  { id: "AP_023", layer: 3, name: "MAINTENANCE_ACCRUAL_MISSING", fileType: "aged_creditors", category: "month_end", severity: "low", confidence: "medium", type: "keyword", field: ["supplier","vendor"], keywords: ["maintenance","service contract","support","subscription","annual contract"], nameField: ["supplier","vendor"], message: "Review reminder: maintenance or service supplier detected", description: "Maintenance contracts and subscriptions are normally recurring, but supplier presence alone is not a missing accrual.", detail: "Service/maintenance supplier(s) identified: {{names}}", impact: "Review reminder — recurring contract accrual may be required", recommendation: "Review maintenance and subscription contracts and accrue only for uninvoiced services received.", evidenceStrength: "advisory" },
  { id: "AP_024", layer: 3, name: "AP_DEBIT_BALANCE_OVER_30_DAYS", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "high", type: "sign", field: ["balance","amount"], keywords: ["negative"], threshold: 1000, nameField: ["supplier","vendor"], message: "{{count}} supplier credit (debit) balances outstanding over time", description: "Debit balances on supplier accounts that remain unclaimed may become irrecoverable.", detail: "{{count}} suppliers with debit balances (potential overpayment).", impact: "Recovery opportunity — claim before balances are forgotten", recommendation: "Contact suppliers with debit balances and request refund or credit note." },
  { id: "AP_025", layer: 3, name: "LARGE_UNCLEARED_AP_CASHFLOW", fileType: "aged_creditors", category: "cashflow", severity: "high", confidence: "medium", type: "aging", dateField: ["date","invoice_date"], days: 60, nameField: ["supplier","vendor"], message: "Large volume of uncleared AP items — cash flow commitment risk", description: "A high total of outstanding AP creates a significant cash flow commitment in the near term.", detail: "{{count}} uncleared AP items aged 60+ days totalling {{total}}.", impact: "{{total}} cash flow commitment from overdue AP", recommendation: "Prepare AP payment schedule — plan cash flow to meet obligations without causing liquidity strain." },
  { id: "AP_026", layer: 3, name: "EMPLOYEE_EXPENSE_LARGE", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["supplier","description","account_name"], keywords: ["employee","staff","expenses","expense claim","reimbursement"], nameField: ["supplier","vendor"], message: "{{count}} employee expense reimbursements in AP — {{total}}", description: "Employee expense claims in the AP ledger should be reviewed for policy compliance and receipts.", detail: "{{count}} employee expense entries totalling {{total}}.", impact: "Expense policy compliance risk", recommendation: "Review employee expense claims against policy limits — confirm receipts and management approval." },
  { id: "AP_027", layer: 3, name: "OVERSEAS_SUPPLIER_WITHHOLDING_TAX", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["supplier","description"], keywords: ["overseas","foreign","international","import","non-uk","eu supplier"], nameField: ["supplier","vendor"], message: "{{count}} overseas supplier invoices — withholding tax review required", description: "Payments to overseas suppliers may be subject to withholding tax under double tax treaties.", detail: "{{count}} overseas supplier invoices identified: {{names}}", impact: "Withholding tax compliance risk", recommendation: "Review treaty obligations and withholding tax requirements for overseas supplier payments." },
  { id: "AP_028", layer: 3, name: "SINGLETON_SUPPLIER_HIGH_VALUE", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "threshold", field: ["amount","balance"], comparator: "gt", threshold: 25000, nameField: ["supplier","vendor"], message: "{{count}} suppliers with a single large invoice — no trading history", description: "One-off suppliers with a single high-value invoice have no payment history to validate legitimacy.", detail: "{{count}} single-invoice suppliers with amounts over £25,000.", impact: "Vendor legitimacy risk", recommendation: "Perform enhanced due diligence on single-invoice suppliers — verify company registration and bank details." },
  { id: "AP_029", layer: 3, name: "AGED_CREDITORS_PAST_YEAR_END", fileType: "aged_creditors", category: "month_end", severity: "high", confidence: "medium", type: "keyword", field: ["status","description"], keywords: ["carry over","rolled","prior year","brought forward","b/f"], nameField: ["supplier","vendor"], message: "{{count}} AP items appear to be carried over from prior year", description: "AP items from the prior year that remain uncleared may require year-end adjustments or disclosure.", detail: "{{count}} possible prior-year AP items still outstanding.", impact: "Prior year AP items require year-end review", recommendation: "Review all prior-year AP items — clear, dispute or disclose as appropriate in the financial statements." },
  { id: "AP_030", layer: 3, name: "TELECOMS_SUBSCRIPTION_ACCRUAL", fileType: "aged_creditors", category: "month_end", severity: "low", confidence: "medium", type: "keyword", field: ["supplier","vendor"], keywords: ["broadband","telephone","mobile","telecoms","bt ","virgin","o2","vodafone","ee ","three ","sky"], nameField: ["supplier","vendor"], message: "Review reminder: telecoms supplier detected", description: "Monthly telecoms and broadband invoices are recurring, but supplier presence alone is not a missing accrual.", detail: "Telecoms supplier(s) identified: {{names}}", impact: "Review reminder — monthly telecoms accrual may be required", recommendation: "Check telecoms invoice timing and accrue only for uninvoiced usage.", evidenceStrength: "advisory" },
  { id: "AP_031", layer: 3, name: "GOVERNMENT_DUTY_MISSING", fileType: "aged_creditors", category: "month_end", severity: "medium", confidence: "medium", type: "keyword", field: ["supplier","vendor","description"], keywords: ["hmrc","customs","duty","import duty","excise","corporation tax","paye"], nameField: ["supplier","vendor"], message: "Government or HMRC payment items in AP — {{total}}", description: "HMRC and government duty payments require careful review for correct coding and timeliness.", detail: "{{count}} HMRC/government AP items totalling {{total}}.", impact: "Regulatory payment compliance", recommendation: "Confirm HMRC payment amounts and due dates — ensure timely payment to avoid penalties." },
  { id: "AP_032", layer: 3, name: "CREDIT_CARD_CLEARING_OUTSTANDING", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["supplier","vendor","description"], keywords: ["credit card","amex","visa","mastercard","corporate card","company card"], nameField: ["supplier","vendor"], message: "Credit card clearing account has outstanding balance", description: "Credit card clearing accounts should be cleared monthly — an outstanding balance indicates unallocated card transactions.", detail: "{{count}} credit card clearing items found: {{total}}", impact: "Unallocated corporate card expenditure", recommendation: "Allocate all credit card transactions to correct nominal codes and clear the clearing account." },
  { id: "AP_033", layer: 3, name: "AP_GOODS_RECEIVED_NOT_INVOICED", fileType: "aged_creditors", category: "month_end", severity: "medium", confidence: "low", type: "keyword", field: ["description","account_name","status"], keywords: ["grni","goods received","received not invoiced","accrued invoice","uninvoiced"], nameField: ["supplier","vendor"], message: "{{count}} goods received not invoiced (GRNI) items outstanding", description: "GRNI balances represent goods received but not yet invoiced — these are accrued liabilities.", detail: "{{count}} GRNI items identified: {{total}}", impact: "GRNI accruals require review and sign-off", recommendation: "Review GRNI listing — confirm matching invoices are expected and post any required accruals." },
  { id: "AP_034", layer: 3, name: "SUBCONTRACTOR_CIS_DEDUCTION", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["supplier","description"], keywords: ["subcontractor","sub-contractor","cis","construction","labour only"], nameField: ["supplier","vendor"], message: "{{count}} subcontractor invoices — CIS deduction review required", description: "Payments to construction subcontractors may be subject to CIS (Construction Industry Scheme) deductions.", detail: "{{count}} subcontractor invoices identified: {{names}}", impact: "CIS non-compliance risk", recommendation: "Verify CIS registration and deduction status for all construction subcontractors." },
  { id: "AP_035", layer: 3, name: "MANAGEMENT_FEE_MISSING", fileType: "aged_creditors", category: "month_end", severity: "low", confidence: "medium", type: "keyword", field: ["supplier","description"], keywords: ["management fee","management charge","head office","group management"], nameField: ["supplier","vendor"], message: "Review reminder: management fee supplier detected", description: "Group management fees are typically charged monthly, but supplier presence alone is not a missing accrual.", detail: "Management fee supplier(s) identified: {{names}}", impact: "Review reminder — management fee accrual may be required", recommendation: "Confirm management fee agreement terms and accrue only where invoice timing requires it.", evidenceStrength: "advisory" },
  { id: "AP_036", layer: 3, name: "SUPPLIER_PAYMENT_TERMS_COMPLIANCE", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "medium", type: "aging", dateField: ["due_date"], days: 7, nameField: ["supplier","vendor"], message: "{{count}} supplier invoices past their due date — {{total}}", description: "Invoices past their due date risk supplier credit terms being withdrawn and relationship damage.", detail: "{{count}} invoices past due date totalling {{total}}.", impact: "Supplier relationship and credit terms at risk", recommendation: "Prioritise payment of invoices past their due date — communicate with key suppliers." },
  { id: "AP_037", layer: 3, name: "LEASING_OBLIGATIONS_MISSING", fileType: "aged_creditors", category: "month_end", severity: "medium", confidence: "low", type: "keyword", field: ["supplier","description"], keywords: ["lease","hire purchase","finance lease","operating lease","pcp","balloon payment"], nameField: ["supplier","vendor"], message: "Lease or hire purchase obligations in AP — IFRS 16 review", description: "Lease liabilities must be correctly classified under IFRS 16 or FRS 102 — may require right-of-use asset recognition.", detail: "{{count}} lease-related payables identified: {{names}}", impact: "IFRS 16 / FRS 102 disclosure required", recommendation: "Review lease classifications and confirm IFRS 16 or FRS 102 treatment is correctly applied." },
  { id: "AP_038", layer: 3, name: "FOREIGN_CURRENCY_AP", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "high", type: "keyword", field: ["currency"], keywords: ["USD","EUR","CHF","JPY","AED","AUD","CAD"], nameField: ["supplier","vendor"], message: "{{count}} foreign currency AP invoices — FX revaluation required", description: "Foreign currency payables must be revalued at the period-end exchange rate.", detail: "{{count}} foreign currency invoices in AP: {{total}}", impact: "FX revaluation required for accurate liabilities", recommendation: "Revalue all foreign currency AP balances at period-end exchange rate — post FX gain/loss." },
  { id: "AP_039", layer: 3, name: "ACCRUED_HOLIDAY_PAY_MISSING", fileType: "aged_creditors", category: "month_end", severity: "medium", confidence: "low", type: "keyword", field: ["description","account_name"], keywords: ["holiday pay","annual leave","vacation accrual","pto","leave accrual"], nameField: ["supplier","vendor"], message: "Holiday pay accrual check — confirm included in AP or accruals", description: "Accrued holiday entitlement earned but untaken must be accrued as a liability at period end.", detail: "Holiday pay accrual indicator detected.", impact: "Holiday pay accrual may be understated", recommendation: "Confirm holiday pay accrual has been calculated and posted for all staff with untaken annual leave.", evidenceStrength: "advisory" },
  { id: "AP_040", layer: 3, name: "AP_CONTROL_ACCOUNT_CHECK", fileType: "aged_creditors", category: "data_quality", severity: "high", confidence: "medium", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 1000000, nameField: ["supplier","vendor"], message: "Total AP outstanding is very high — confirm reconciled to TB", description: "Very high total AP balances require reconciliation to the TB creditors control account.", detail: "Total AP outstanding exceeds £1,000,000 — TB reconciliation required.", impact: "AP integrity check required", recommendation: "Reconcile total aged creditors to the TB creditors control account before sign-off.", evidenceStrength: "deterministic" },
  { id: "AP_041", layer: 3, name: "DUPLICATE_SUPPLIER_AMOUNT_DATE", fileType: "aged_creditors", category: "ap", severity: "high", confidence: "high", type: "ledger_metric", ledgerMetric: "duplicate_party_amount_date", nameField: ["supplier","vendor"], message: "Duplicate supplier/date/amount combinations detected — duplicate payment risk", description: "Same supplier, same date and same amount appearing more than once can indicate duplicate invoices even when references differ.", detail: "Duplicate supplier/date/amount groups identified in AP.", impact: "Duplicate payment risk requiring immediate hold", recommendation: "Hold duplicate payment groups pending supplier statement reconciliation and invoice image review.", evidenceStrength: "deterministic" },
  { id: "AP_045", layer: 3, name: "TOP_5_SUPPLIERS_OVER_80PCT", fileType: "aged_creditors", category: "ap", severity: "medium", confidence: "high", type: "ledger_metric", ledgerMetric: "top_five_party_concentration", threshold: 0.8, nameField: ["supplier","vendor"], message: "Top five suppliers exceed 80% of AP exposure", description: "High AP concentration with a small number of suppliers creates payment, negotiation and supply chain dependency risk.", detail: "Top suppliers represent more than 80% of AP outstanding.", impact: "Supplier concentration and cash planning risk", recommendation: "Review supplier concentration, negotiate payment plans and ensure continuity plans exist for critical suppliers.", evidenceStrength: "deterministic" },
];

const deterministicAp = new Set([
  "AP_001",
  "AP_002",
  "AP_003",
  "AP_004",
  "AP_005",
  "AP_007",
  "AP_022",
  "AP_024",
  "AP_025",
  "AP_036",
  "AP_038",
  "AP_040",
  "AP_041",
  "AP_045",
]);

const supplierRiskIndicators = new Set([
  "AP_006",
  "AP_008",
  "AP_009",
  "AP_010",
  "AP_011",
  "AP_012",
  "AP_013",
  "AP_014",
  "AP_018",
  "AP_019",
  "AP_020",
  "AP_026",
  "AP_028",
  "AP_029",
  "AP_031",
  "AP_032",
  "AP_033",
  "AP_034",
  "AP_037",
]);

const reviewPrompts = new Set([
  "AP_015",
  "AP_016",
  "AP_017",
  "AP_021",
  "AP_023",
  "AP_027",
  "AP_030",
  "AP_035",
  "AP_039",
]);

function normaliseApRule(rule: AssuranceRule): AssuranceRule {
  if (deterministicAp.has(rule.id)) {
    return { ...rule, evidenceStrength: "deterministic" };
  }

  if (supplierRiskIndicators.has(rule.id)) {
    return { ...rule, evidenceStrength: "indicator" };
  }

  if (reviewPrompts.has(rule.id)) {
    return {
      ...rule,
      severity: "low",
      confidence: "low",
      evidenceStrength: "advisory",
      message: rule.message.startsWith("Review prompt:") ? rule.message : `Review prompt: ${rule.message.replace(/^Review reminder:\s*/i, "")}`,
      impact: rule.impact?.startsWith("Review prompt") ? rule.impact : `Review prompt — ${rule.impact ?? "consider month-end accrual or disclosure implications"}`,
    };
  }

  return { ...rule, evidenceStrength: rule.evidenceStrength ?? "indicator" };
}

export const apIntelligenceRules: AssuranceRule[] = apIntelligenceRulesRaw.map(normaliseApRule);
