import type { AssuranceRule } from "@/lib/types/rule";

// Layer 2 — AR Intelligence Engine: 30 rules
// Purpose: Can the business collect its money?

const arIntelligenceRulesRaw: AssuranceRule[] = [
  { id: "AR_001", layer: 2, name: "INVOICE_OVER_60_DAYS", fileType: "aged_debtors", category: "ar", severity: "high", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: 60, message: "{{count}} invoices overdue 60+ days — {{total}} outstanding", description: "Invoices outstanding over 60 days require escalated collection action.", detail: "{{count}} invoices aged 60+ days with total outstanding of {{total}}.", impact: "{{total}} at risk from delayed collections", recommendation: "Escalate collection action for all 60+ day invoices — contact customers and agree payment plans." },
  { id: "AR_002", layer: 2, name: "INVOICE_OVER_90_DAYS", fileType: "aged_debtors", category: "ar", severity: "high", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: 90, message: "{{count}} invoices overdue 90+ days — {{total}} at high collection risk", description: "Invoices outstanding over 90 days are at high risk of becoming irrecoverable.", detail: "{{count}} invoices aged 90+ days. Consider provision at this stage.", impact: "{{total}} high collection risk", recommendation: "Issue formal demand letters — escalate to senior management and legal if not resolved." },
  { id: "AR_003", layer: 2, name: "INVOICE_OVER_120_DAYS", fileType: "aged_debtors", category: "ar", severity: "critical", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: 120, message: "{{count}} invoices overdue 120+ days — {{total}} likely irrecoverable", description: "Invoices over 120 days are at serious risk of irrecoverability and may require provision.", detail: "{{count}} invoices aged 120+ days totalling {{total}}. Provision review required.", impact: "{{total}} — bad debt provision may be required", recommendation: "Assess recoverability and post bad debt provision. Consider legal action or debt collection agency." },
  { id: "AR_004", layer: 2, name: "INVOICE_OVER_180_DAYS", fileType: "aged_debtors", category: "ar", severity: "critical", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: 180, message: "{{count}} invoices overdue 180+ days — {{total}} — write-off review required", description: "Invoices over 180 days outstanding are typically irrecoverable and should be written off or fully provided against.", detail: "{{count}} invoices aged 180+ days. Write-off consideration required.", impact: "{{total}} — write-off or full provision required", recommendation: "Write off or provide 100% against balances over 180 days unless strong evidence of collectability." },
  { id: "AR_005", layer: 2, name: "INVOICE_OVER_365_DAYS", fileType: "aged_debtors", category: "ar", severity: "critical", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: 365, message: "{{count}} invoices over 1 year old — {{total}} — stale and likely irrecoverable", description: "Invoices outstanding over 12 months are almost certainly irrecoverable unless specific circumstances exist.", detail: "{{count}} invoices aged 365+ days totalling {{total}}.", impact: "{{total}} — full write-off likely required", recommendation: "Write off all invoices over 12 months. Board approval required. Review VAT bad debt relief eligibility." },
  { id: "AR_006", layer: 2, name: "CUSTOMER_OVER_CREDIT_LIMIT", fileType: "aged_debtors", category: "ar", severity: "high", confidence: "high", type: "comparison", field: ["balance","outstanding","amount"], referenceField: ["credit_limit","limit","approved_limit"], comparator: "gt", nameField: ["customer","account_name"], message: "{{count}} customers exceed their approved credit limit", description: "Customers trading above their credit limit create uncontrolled credit exposure.", detail: "{{count}} customers have outstanding balances exceeding their credit limit: {{names}}", impact: "Unauthorised credit exposure", recommendation: "Place affected accounts on credit hold and seek management approval before further sales on credit." },
  { id: "AR_007", layer: 2, name: "NEGATIVE_AR_BALANCE", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "high", type: "sign", field: ["balance","outstanding","amount"], keywords: ["negative"], message: "{{count}} customers have negative AR balances — {{total}} credit balance", description: "Negative AR balances indicate credit notes exceed invoices or customers have overpaid.", detail: "{{count}} debtors with net credit balance totalling {{total}}.", impact: "{{total}} refund or netting opportunity", recommendation: "Issue refunds or offset credit balances against future invoices." },
  { id: "AR_008", layer: 2, name: "SINGLE_CUSTOMER_OVER_25PCT", fileType: "aged_debtors", category: "ar", severity: "high", confidence: "high", type: "ledger_metric", ledgerMetric: "single_party_concentration", threshold: 0.25, nameField: ["customer","account_name"], message: "Debtor concentration risk — single customer exceeds 25% of AR", description: "When one customer represents more than 25% of total AR, collection failure creates material cash flow risk.", detail: "A single customer accounts for over 25% of total AR outstanding.", impact: "Material concentration risk from single debtor", recommendation: "Reduce concentration risk — diversify customer base, set active collection ownership and review credit insurance options.", evidenceStrength: "deterministic" },
  { id: "AR_009", layer: 2, name: "TOP_5_CUSTOMERS_OVER_60PCT", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "high", type: "ledger_metric", ledgerMetric: "top_five_party_concentration", threshold: 0.6, nameField: ["customer","account_name"], message: "Top five customers exceed 60% of AR", description: "Heavy reliance on a small number of customers for the majority of AR creates concentration risk.", detail: "Top customers represent a high proportion of total AR outstanding.", impact: "Portfolio concentration risk", recommendation: "Monitor top customer payment behaviour closely, assign owner-level collection actions and consider credit insurance.", evidenceStrength: "deterministic" },
  { id: "AR_010", layer: 2, name: "DISPUTED_INVOICES_OUTSTANDING", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "high", type: "keyword", field: ["status"], keywords: ["disput","dispute","on hold","query","query","stopped","blocked"], nameField: ["customer","account_name"], message: "{{count}} customers with disputed or on-hold invoices — {{total}}", description: "Disputed invoices require formal resolution before they can be collected or written off.", detail: "{{count}} accounts have outstanding balances in disputed or on-hold status: {{names}}", impact: "{{total}} in dispute — may not be collectable", recommendation: "Formally resolve all disputed invoices — obtain written resolution or escalate." },
  { id: "AR_011", layer: 2, name: "CUSTOMER_OVER_LIMIT_CRITICAL", fileType: "aged_debtors", category: "ar", severity: "critical", confidence: "high", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 100000, nameField: ["customer","account_name"], message: "{{count}} customers with balances exceeding £100,000", description: "Very large single-customer exposures require board-level awareness and active collection management.", detail: "{{count}} customers have individual balances exceeding £100,000: {{names}}", impact: "{{total}} — board-level collection management required", recommendation: "Escalate to CFO or board — assign dedicated collection resource to large balance accounts." },
  { id: "AR_012", layer: 2, name: "HIGH_DAYS_SALES_OUTSTANDING", fileType: "aged_debtors", category: "cashflow", severity: "high", confidence: "medium", type: "threshold", field: ["days","age","days_overdue","aging"], comparator: "gt", threshold: 60, nameField: ["customer","account_name"], message: "{{count}} customers have debtor days exceeding 60 days", description: "High debtor days indicate slow payment culture or collections weakness.", detail: "{{count}} customers with debtor days > 60: {{names}}", impact: "Working capital pressure from slow collections", recommendation: "Review collection processes — implement automated payment reminders and payment terms enforcement." },
  { id: "AR_013", layer: 2, name: "PARTIAL_PAYMENT_PATTERN", fileType: "aged_debtors", category: "ar", severity: "low", confidence: "low", type: "keyword", field: ["description","status","memo"], keywords: ["partial","part pay","instalment","plan","arrangement"], nameField: ["customer","account_name"], message: "{{count}} customers on payment plans or making partial payments", description: "Customers making only partial payments may be in financial difficulty.", detail: "{{count}} accounts show partial payment or instalment arrangement indicators.", impact: "Collection risk — monitor closely", recommendation: "Review payment plan terms — escalate if arrangements are not being maintained." },
  { id: "AR_014", layer: 2, name: "NEW_CUSTOMER_LARGE_INVOICE", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "low", type: "keyword", field: ["customer"], keywords: ["new","first","trial","initial"], nameField: ["customer","account_name"], message: "{{count}} possible new customers with large outstanding invoices", description: "New or first-time customers with large outstanding invoices may not have been through full credit approval.", detail: "{{count}} accounts with 'new' or 'first' customer indicators have significant balances.", impact: "Credit approval may not have been completed", recommendation: "Confirm new customer credit assessments are complete and limits are approved." },
  { id: "AR_015", layer: 2, name: "AR_MATERIAL_BALANCE_NO_CONTACT", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "low", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 25000, nameField: ["customer","account_name"], message: "{{count}} customers with balances over £25,000 requiring review", description: "Material debtor balances over £25,000 warrant specific attention and documented collection activity.", detail: "{{count}} customers have balances exceeding £25,000: {{names}}", impact: "{{total}} requiring active collection management", recommendation: "Document collection activity for all balances over £25,000 — include in management reporting." },
  { id: "AR_016", layer: 2, name: "INVOICE_BEFORE_ORDER", fileType: "aged_debtors", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["description","invoice_ref","reference"], keywords: ["pre-invoice","proforma","advance","upfront","deposit"], nameField: ["customer","account_name"], message: "{{count}} possible pre-invoices or advance billing in AR", description: "Pre-invoicing or advance billing before delivery raises revenue recognition questions.", detail: "{{count}} invoices appear to be advance or pre-billed.", impact: "Revenue recognition review required", recommendation: "Confirm revenue recognition basis for advance-billed invoices." },
  { id: "AR_017", layer: 2, name: "CUSTOMER_HAS_BOTH_LARGE_INVOICES_AND_CREDIT_NOTES", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "low", type: "sign", field: ["amount","balance"], keywords: ["negative"], nameField: ["customer","account_name"], message: "{{count}} customers with both invoices and credit balances — potential netting opportunity", description: "Customers with both debit and credit balances on different invoices may benefit from netting.", detail: "{{count}} customers with mixed invoice and credit positions.", impact: "Working capital can be improved by netting", recommendation: "Net off debits and credits within the same customer account." },
  { id: "AR_018", layer: 2, name: "LARGE_INVOICE_DUE_THIS_WEEK", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "medium", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 10000, nameField: ["customer","account_name"], message: "{{count}} material invoices (>£10,000) due imminently", description: "Large invoices approaching due date require proactive collection action.", detail: "{{count}} invoices over £10,000 are approaching or have passed due date.", impact: "{{total}} — proactive collection required", recommendation: "Contact customers with large imminent invoices — confirm payment will be made on time." },
  { id: "AR_019", layer: 2, name: "AR_OVERSEAS_CUSTOMER", fileType: "aged_debtors", category: "ar", severity: "low", confidence: "low", type: "keyword", field: ["customer","account_name"], keywords: ["international","overseas","export","foreign","global"], nameField: ["customer","account_name"], message: "{{count}} overseas customers in AR — currency risk", description: "Overseas customers with GBP invoices may face FX risk if their home currency weakens.", detail: "{{count}} overseas customer accounts identified.", impact: "FX and collection risk on overseas debtors", recommendation: "Review FX exposure on overseas customer balances — consider FX hedging or currency invoicing." },
  { id: "AR_020", layer: 2, name: "GOVERNMENT_OR_PUBLIC_SECTOR_DEBT", fileType: "aged_debtors", category: "ar", severity: "low", confidence: "low", type: "keyword", field: ["customer","account_name"], keywords: ["council","nhs","government","local authority","ministry","department","trust","public sector","authority"], nameField: ["customer","account_name"], message: "{{count}} public sector debtors in AR", description: "Public sector debtors are generally lower credit risk but can have slow payment processes.", detail: "{{count}} public sector customer accounts identified.", impact: "Monitor for payment delays — follow up on prompt payment code obligations", recommendation: "Track public sector payment timelines and reference prompt payment obligations in follow-up." },
  { id: "AR_021", layer: 2, name: "HIGH_VALUE_INVOICE_WITHOUT_PO", fileType: "aged_debtors", category: "controls", severity: "medium", confidence: "low", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 50000, message: "{{count}} high-value invoices (>£50,000) — confirm PO reference exists", description: "High-value invoices without a purchase order reference may be disputed by the customer.", detail: "{{count}} invoices exceeding £50,000 found in aged debtors.", impact: "Dispute risk on large invoices without PO", recommendation: "Confirm all invoices over £50,000 have a corresponding customer PO reference." },
  { id: "AR_022", layer: 2, name: "CUSTOMER_PAYMENT_TERMS_BREACH", fileType: "aged_debtors", category: "ar", severity: "high", confidence: "medium", type: "comparison", field: ["days","age","days_overdue"], referenceField: ["payment_terms","credit_days","terms"], comparator: "gt", nameField: ["customer","account_name"], message: "{{count}} customers in breach of payment terms", description: "Customers paying beyond agreed payment terms are in breach of their credit agreement.", detail: "{{count}} customers have outstanding days exceeding their agreed payment terms.", impact: "Payment term breaches require escalation", recommendation: "Issue formal breach-of-terms letters to non-compliant customers." },
  { id: "AR_023", layer: 2, name: "RETENTIONS_OUTSTANDING", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "medium", type: "keyword", field: ["description","account_name","invoice_ref"], keywords: ["retention","retainer","defect","defects liability","snagging","hold-back"], nameField: ["customer","account_name"], message: "{{count}} retention amounts in AR — {{total}}", description: "Retention amounts may be released only after contract completion or defect liability periods.", detail: "{{count}} invoices identified as retention or defects liability amounts: {{total}}", impact: "{{total}} — review release conditions", recommendation: "Review contract terms for retention release conditions — schedule release diary dates." },
  { id: "AR_024", layer: 2, name: "INTERCOMPANY_AR_OUTSTANDING", fileType: "aged_debtors", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["customer","account_name"], keywords: ["intercompany","intra-group","related party","group company","sister","subsidiary","parent"], nameField: ["customer","account_name"], message: "{{count}} intercompany receivables outstanding — {{total}}", description: "Intercompany receivables must be confirmed with the counterpart entity and eliminated on consolidation.", detail: "{{count}} intercompany AR balances identified: {{names}}", impact: "Consolidation elimination required", recommendation: "Confirm intercompany balances with counterpart entities — eliminate on consolidation." },
  { id: "AR_025", layer: 2, name: "AR_BALANCE_EXCEEDS_PRIOR_QUARTER", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "low", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 500000, message: "Total AR outstanding is very high — {{total}}", description: "A very high total AR balance relative to expected revenue may indicate collection problems or over-trading.", detail: "Total AR outstanding is {{total}} — review against revenue level.", impact: "Working capital is tied up in receivables", recommendation: "Review total AR as a percentage of annual revenue — target below 10% of turnover." },
  { id: "AR_026", layer: 2, name: "LEGAL_ACTION_ACCOUNTS", fileType: "aged_debtors", category: "ar", severity: "high", confidence: "high", type: "keyword", field: ["status","description"], keywords: ["legal","solicitor","court","ccj","winding up","administration","insolvency","receiver"], nameField: ["customer","account_name"], message: "{{count}} accounts subject to legal action or insolvency — {{total}}", description: "Customers in legal proceedings or insolvency may not pay — immediate provision required.", detail: "{{count}} accounts with legal/insolvency indicators: {{names}}", impact: "{{total}} — provision or write-off required immediately", recommendation: "Provision 100% against accounts in insolvency. Register as creditor in insolvency proceedings." },
  { id: "AR_027", layer: 2, name: "SEASONAL_CUSTOMER_ANOMALY", fileType: "aged_debtors", category: "ar", severity: "low", confidence: "low", type: "threshold", field: ["amount","balance"], comparator: "gt", threshold: 0, message: "Seasonal customer concentration detected in AR", description: "Highly seasonal customer balances may indicate timing risk in collections.", detail: "Multiple customers with similar invoice timing patterns.", impact: "Seasonal cash flow risk from concentrated invoicing", recommendation: "Review seasonal billing patterns and ensure payment terms align with customer payment cycles.", evidenceStrength: "advisory" },
  { id: "AR_028", layer: 2, name: "HIGH_CREDIT_NOTE_ACTIVITY", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "medium", type: "sign", field: ["amount","balance"], keywords: ["negative"], threshold: 5000, message: "{{count}} significant credit note balances in AR — {{total}}", description: "High levels of credit note activity may indicate disputes, quality issues or revenue recognition problems.", detail: "{{count}} credit balance entries exceeding £5,000 in the AR ledger.", impact: "Revenue quality review required", recommendation: "Review credit note volumes — investigate root causes if credit notes are a high proportion of invoiced revenue." },
  { id: "AR_029", layer: 2, name: "UNBILLED_WORK_IN_PROGRESS", fileType: "aged_debtors", category: "month_end", severity: "medium", confidence: "low", type: "keyword", field: ["description","account_name"], keywords: ["wip","work in progress","unbilled","accrued income","accrued revenue","contract asset"], nameField: ["customer","account_name"], message: "{{count}} unbilled WIP or accrued income items in AR — {{total}}", description: "Unbilled WIP requires review to ensure revenue recognition criteria have been met.", detail: "{{count}} WIP or accrued income items identified: {{total}}", impact: "Revenue recognition review required", recommendation: "Review WIP valuation and confirm revenue recognition basis before sign-off." },
  { id: "AR_030", layer: 2, name: "AR_DEFERRED_INCOME_RISK", fileType: "aged_debtors", category: "month_end", severity: "medium", confidence: "low", type: "keyword", field: ["description","account_name","invoice_ref"], keywords: ["advance","deposit","prepay","stage payment","milestone","phase"], nameField: ["customer","account_name"], message: "{{count}} advance or stage payment invoices — deferred income review required", description: "Advance payments received before work is complete should be recognised as deferred income until earned.", detail: "{{count}} advance/stage payment invoices identified in AR.", impact: "Deferred income may be understated", recommendation: "Confirm all advance payments received are classified as deferred income until performance obligations are met." },
];

const deterministicAr = new Set([
  "AR_001",
  "AR_002",
  "AR_003",
  "AR_004",
  "AR_005",
  "AR_006",
  "AR_007",
  "AR_008",
  "AR_009",
  "AR_011",
  "AR_022",
  "AR_026",
  "AR_028",
]);

const collectionIndicators = new Set([
  "AR_010",
  "AR_012",
  "AR_013",
  "AR_014",
  "AR_015",
  "AR_016",
  "AR_017",
  "AR_018",
  "AR_021",
  "AR_023",
  "AR_024",
  "AR_025",
  "AR_029",
  "AR_030",
]);

const businessInsightReminders = new Set([
  "AR_019",
  "AR_020",
  "AR_027",
]);

function normaliseArRule(rule: AssuranceRule): AssuranceRule {
  if (deterministicAr.has(rule.id)) {
    return { ...rule, evidenceStrength: "deterministic" };
  }

  if (collectionIndicators.has(rule.id)) {
    return { ...rule, evidenceStrength: "indicator" };
  }

  if (businessInsightReminders.has(rule.id)) {
    return {
      ...rule,
      severity: "low",
      confidence: "low",
      evidenceStrength: "advisory",
      message: rule.message.startsWith("Business insight:") ? rule.message : `Business insight: ${rule.message}`,
      impact: rule.impact?.startsWith("Business insight") ? rule.impact : `Business insight — ${rule.impact ?? "monitor for collection timing implications"}`,
    };
  }

  return { ...rule, evidenceStrength: rule.evidenceStrength ?? "indicator" };
}

export const arIntelligenceRules: AssuranceRule[] = arIntelligenceRulesRaw.map(normaliseArRule);
