import type { AssuranceRule } from "@/lib/types/rule";

// Layer 7 — Controls & Fraud Engine: 60 rules
// Purpose: Continuous financial assurance and fraud detection.

const controlsFraudRulesRaw: AssuranceRule[] = [
  { id: "CF_001", layer: 7, name: "WEEKEND_TRANSACTION", fileType: "any", category: "controls", severity: "medium", confidence: "high", type: "keyword", field: ["posting_date","entry_date","created_date"], keywords: ["Saturday","Sunday","weekend"], nameField: ["account_name","description"], message: "{{count}} transactions posted on a weekend — authorisation review required", description: "Weekend postings above £1,000 are unusual and may indicate unauthorised access or emergency adjustments.", detail: "{{count}} entries were posted on a Saturday or Sunday.", impact: "Weekend posting authorisation must be confirmed", recommendation: "Investigate all weekend postings above £1,000 — confirm authorisation and business reason." },
  { id: "CF_002", layer: 7, name: "ROUND_NUMBER_SPIKE", fileType: "any", category: "controls", severity: "low", confidence: "low", type: "percentage", field: ["amount","balance","debit","credit"], keywords: [], percentage: 25, message: "High proportion of round-number transactions (>25%) — estimation risk", description: "When more than 25% of all transactions are exact multiples of £1,000, it may indicate estimated rather than actual figures.", detail: "{{count}} transactions ({{pct}}) are round-number multiples of £1,000.", impact: "Estimation risk — verify amounts are actual invoiced values", recommendation: "Review round-number transactions — replace estimates with actual amounts where possible." },
  { id: "CF_003", layer: 7, name: "LARGE_UNUSUAL_JOURNAL", fileType: "trial_balance", category: "controls", severity: "high", confidence: "medium", type: "threshold", field: ["balance","amount","debit","credit"], comparator: "gt", threshold: 500000, nameField: ["account_name","description"], message: "{{count}} very large journal entries (>£500,000) — board review recommended", description: "Transactions over £500,000 are material and warrant specific board or senior management review.", detail: "{{count}} entries exceeding £500,000 detected.", impact: "Material entries require board-level visibility", recommendation: "Present all entries over £500,000 to the board or audit committee for review and approval." },
  { id: "CF_004", layer: 7, name: "USER_SINGLE_LARGE_POSTING", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["posted_by","created_by","user","entered_by"], keywords: ["admin","administrator","system","default","root","super user","superuser"], nameField: ["account_name","description"], message: "System or administrator user account posted material entries", description: "Material postings by system or admin accounts bypass normal user controls and segregation of duties.", detail: "Entries posted by system/admin user accounts detected.", impact: "Segregation of duties failure", recommendation: "Review all entries posted by admin/system accounts — implement user-level posting controls.", evidenceStrength: "indicator" },
  { id: "CF_005", layer: 7, name: "DUPLICATE_PAYMENT_INVOICE_REF", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "high", type: "ledger_metric", ledgerMetric: "duplicate_reference", field: ["invoice_ref","reference","ref"], nameField: ["supplier","vendor"], message: "Duplicate invoice references detected in AP — duplicate payment risk", description: "The same supplier/reference combination appearing more than once is the most common cause of duplicate payments.", detail: "Duplicate invoice references found in the AP ledger.", impact: "Duplicate payment may have been made", recommendation: "Investigate all duplicate invoice references — recover any overpayments from suppliers.", evidenceStrength: "deterministic" },
  { id: "CF_006", layer: 7, name: "INVOICE_DATE_AFTER_POSTING", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "high", type: "comparison", field: ["posting_date","entry_date"], referenceField: ["invoice_date","date"], comparator: "lt", nameField: ["supplier","vendor"], message: "{{count}} invoices posted before their invoice date (backdated posting)", description: "A posting date before the invoice date indicates backdated entries or system date errors.", detail: "{{count}} entries were posted before the invoice date.", impact: "Backdating controls may be ineffective", recommendation: "Review backdated postings — confirm business reason and obtain management approval." },
  { id: "CF_007", layer: 7, name: "SPLIT_PAYMENT_PATTERN", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "medium", type: "threshold", field: ["amount","balance"], comparator: "lt", threshold: 1000, nameField: ["supplier","vendor"], message: "Possible approval limit avoidance — multiple sub-£1,000 invoices from same supplier", description: "Three or more invoices from the same supplier on the same date, each below £1,000, totalling above that threshold, may indicate deliberate splitting.", detail: "Multiple sub-threshold invoices from the same supplier on the same date detected.", impact: "Approval controls may be bypassed", recommendation: "Review split invoice patterns — implement cumulative approval thresholds to prevent avoidance.", evidenceStrength: "indicator" },
  { id: "CF_008", layer: 7, name: "NEW_VENDOR_PAYMENT", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "medium", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 5000, nameField: ["supplier","vendor"], message: "{{count}} first-time vendor payments over £5,000", description: "New vendors with high-value first invoices require enhanced due diligence — a common vector for invoice fraud.", detail: "{{count}} first-time vendors with invoices over £5,000: {{names}}", impact: "Vendor fraud risk", recommendation: "Call the vendor on a verified number to confirm bank details — do not trust email-only communication." },
  { id: "CF_009", layer: 7, name: "PERSONAL_PAYEE_LARGE_AMOUNT", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "low", type: "threshold", field: ["amount","balance"], comparator: "gt", threshold: 2500, nameField: ["supplier","vendor"], message: "{{count}} large payments to individuals (>£2,500)", description: "Large payments to individual persons rather than companies are a significant fraud and PAYE risk.", detail: "{{count}} payments to individuals exceeding £2,500: {{names}}", impact: "Fraud and PAYE compliance risk", recommendation: "Obtain management approval and IR35/PAYE assessment for all large individual payments." },
  { id: "CF_010", layer: 7, name: "SUSPENSE_ACCOUNT_CLEARED_QUICKLY", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["suspense","clearing","holding"], mustExist: true, threshold: 1, nameField: ["account_name"], message: "Suspense or clearing account balance outstanding", description: "Suspense and clearing accounts should be nil or fully supported before sign-off.", detail: "Suspense/clearing account balances found.", impact: "Close blocker — suspense balances need allocation or support", recommendation: "Allocate all suspense balances to correct nominal codes or document support before sign-off.", evidenceStrength: "indicator" },
  { id: "CF_011", layer: 7, name: "JOURNAL_ENTRY_UNUSUAL_ACCOUNTS", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["error","mistake","wrong","incorrect","reversal","adjustment","correction"], nameField: ["account_name"], message: "{{count}} error or correction journal entries detected", description: "A high number of correction entries may indicate poor data quality or attempts to conceal mispostings.", detail: "{{count}} journal entries with error/correction narrations.", impact: "Data quality and potential concealment risk", recommendation: "Review all correction journals — confirm valid business reason and management approval." },
  { id: "CF_012", layer: 7, name: "ACCOUNTS_WITH_UNUSUAL_DR_CR_BALANCE", fileType: "trial_balance", category: "controls", severity: "low", confidence: "medium", type: "keyword", field: ["account_name"], keywords: ["income","revenue","sales","turnover"], mustExist: true, nameField: ["account_name"], message: "Review reminder: revenue accounts detected — confirm normal credit balance", description: "Revenue accounts normally carry credit balances, but account presence alone cannot prove an unusual balance.", detail: "Revenue accounts detected — verify no debit balances.", impact: "Review reminder — revenue balance direction should be checked", recommendation: "Confirm all revenue accounts have credit balances and investigate any debit balances.", evidenceStrength: "advisory" },
  { id: "CF_013", layer: 7, name: "SEQUENTIAL_INVOICE_GAPS", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["invoice_ref"], keywords: ["INV-","INV ","#"], nameField: ["supplier","vendor"], message: "Sequential invoice number gaps may indicate missing invoices", description: "Gaps in sequential invoice numbering may indicate missing documents or manual deletion of records.", detail: "Invoice number sequence gaps detected in AP.", impact: "Missing invoice documentation", recommendation: "Investigate gaps in invoice number sequences — confirm missing invoices are held in archive.", evidenceStrength: "advisory" },
  { id: "CF_014", layer: 7, name: "DORMANT_SUPPLIER_REACTIVATED", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["status","description"], keywords: ["reactivated","reinstated","previously inactive","formerly dormant"], nameField: ["supplier","vendor"], message: "Previously dormant supplier reactivated — verify legitimacy", description: "Fraudsters sometimes reactivate dormant supplier accounts and update bank details to redirect payments.", detail: "Dormant supplier reactivation indicators found.", impact: "Supplier bank detail fraud risk", recommendation: "Call dormant suppliers on verified numbers before making any payments — re-verify bank account details independently.", evidenceStrength: "advisory" },
  { id: "CF_015", layer: 7, name: "EMPLOYEE_VENDOR_CONFLICT", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["supplier","vendor"], keywords: ["employee","staff","contractor","consultant","freelance"], nameField: ["supplier","vendor"], message: "{{count}} payments to employee-type vendors — conflict of interest check", description: "Payments to suppliers that may be controlled by employees require conflict of interest disclosure and management approval.", detail: "{{count}} vendor entries with employee/contractor indicators: {{names}}", impact: "Conflict of interest and PAYE risk", recommendation: "Confirm all payments to employee-related vendors have been declared in the conflict of interest register." },
  { id: "CF_016", layer: 7, name: "APPROVAL_LIMIT_EXCEEDED", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "medium", type: "threshold", field: ["amount","balance"], comparator: "gt", threshold: 25000, nameField: ["supplier","vendor"], message: "{{count}} AP invoices exceed £25,000 — board/CFO approval confirmation required", description: "Invoices above the board approval threshold require documented evidence of authorisation.", detail: "{{count}} invoices exceeding £25,000 detected.", impact: "Unauthorised expenditure risk above approval limits", recommendation: "Confirm board/CFO approval documentation exists for all invoices above the approval limit." },
  { id: "CF_017", layer: 7, name: "CONTRA_JOURNAL_PATTERN", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["contra","opposite entry","reverse","reversing","netting off"], nameField: ["account_name"], message: "{{count}} contra or reversing journal entries — review for validity", description: "A pattern of contra and reversing journals may be used to temporarily move balances and obscure true positions.", detail: "{{count}} contra/reversing journal entries found.", impact: "Financial manipulation risk", recommendation: "Review contra and reversing journal patterns — confirm they represent valid accounting adjustments." },
  { id: "CF_018", layer: 7, name: "PETTY_CASH_LARGE_ENTRIES", fileType: "trial_balance", category: "controls", severity: "low", confidence: "high", type: "keyword", field: ["account_name"], keywords: ["petty cash","cash float","imprest"], mustExist: true, nameField: ["account_name"], message: "Review reminder: petty cash account detected", description: "Petty cash should be maintained within an approved float amount.", detail: "Petty cash account balance detected.", impact: "Review reminder — petty cash float should be reconciled", recommendation: "Confirm petty cash balance is within approved limit and ensure regular clearance and reconciliation.", evidenceStrength: "advisory" },
  { id: "CF_019", layer: 7, name: "EXPENSE_CLAIM_SPIKE", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["account_name"], keywords: ["expense claim","staff expense","employee expense","mileage claim","travel claim","subsistence claim"], mustExist: true, nameField: ["account_name"], message: "Staff expense claim accounts detected — review for unusual patterns", description: "A sudden spike in staff expense claims may indicate fraudulent claims or a lack of authorisation controls.", detail: "Staff expense claim account(s) detected.", impact: "Expense fraud risk", recommendation: "Review expense claim volumes and individual claim levels — flag unusual patterns for management review.", evidenceStrength: "advisory" },
  { id: "CF_020", layer: 7, name: "CREDIT_CARD_PERSONAL_EXPENSES", fileType: "any", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["description"], keywords: ["personal","private use","non-business","personal purchase","spouse","family"], nameField: ["description","account_name"], message: "{{count}} potential personal expenses on corporate accounts", description: "Personal expenses charged to company accounts are a benefit in kind and must be declared to HMRC.", detail: "{{count}} entries with personal expense indicators.", impact: "BIK liability and expense policy breach", recommendation: "Recover personal expenses from employees — declare any benefits in kind on P11D." },
  { id: "CF_021", layer: 7, name: "ZERO_COST_INVOICE", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "medium", type: "threshold", field: ["amount","balance"], comparator: "eq", threshold: 0, nameField: ["supplier","vendor"], message: "{{count}} zero-value invoices in AP — confirm these are valid", description: "Zero-value invoices with invoice references may be test entries, phantom invoices or cleared items left on the ledger.", detail: "{{count}} zero-amount AP entries with invoice references.", impact: "Phantom invoice risk", recommendation: "Review zero-value invoices — remove test entries and clear legitimate zero-value items." },
  { id: "CF_022", layer: 7, name: "LARGE_CREDIT_NOTE_SUSPICIOUS", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "sign", field: ["amount","balance"], keywords: ["negative"], threshold: 10000, nameField: ["supplier","vendor"], message: "{{count}} large supplier credit notes (>£10,000) — confirm validity", description: "Large credit notes may indicate fraudulent credit note creation to create payable balances for subsequent theft.", detail: "{{count}} credit note entries exceeding £10,000 detected.", impact: "Fraudulent credit note risk", recommendation: "Confirm all large credit notes relate to valid returned goods or price adjustments — verify with supplier." },
  { id: "CF_023", layer: 7, name: "HIGH_VALUE_CASH_TRANSACTIONS", fileType: "trial_balance", category: "controls", severity: "high", confidence: "medium", type: "keyword", field: ["account_name","description"], keywords: ["cash payment","cash receipt","cash transaction","cash sale"], nameField: ["account_name"], message: "High-value cash transactions detected — AML check required", description: "Cash transactions above £10,000 trigger Anti-Money Laundering (AML) reporting obligations.", detail: "High-value cash transaction indicators found.", impact: "AML reporting obligation may apply", recommendation: "Review cash transactions above £10,000 — report to MLRO if suspicious activity is suspected.", evidenceStrength: "indicator" },
  { id: "CF_024", layer: 7, name: "BANK_ACCOUNT_CHANGE_IN_PERIOD", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["description","memo","notes"], keywords: ["new bank","bank change","updated bank","payment details changed","new account number","new sort code"], nameField: ["supplier","vendor"], message: "Supplier bank detail change indicators detected", description: "Bank detail changes should be verified by calling the supplier directly — a major vector for invoice fraud.", detail: "Bank detail change references found for suppliers.", impact: "Invoice fraud — payment redirection risk", recommendation: "Physically call each supplier on a verified number to confirm bank detail changes before processing payment.", evidenceStrength: "advisory" },
  { id: "CF_025", layer: 7, name: "FICTITIOUS_VENDOR_INDICATORS", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["supplier"], keywords: ["PO Box","P.O. Box","box only","no address","c/o","care of","holding company"], nameField: ["supplier","vendor"], message: "{{count}} vendors with PO Box or limited address information", description: "Vendors with only PO Box addresses and no physical address may be fictitious entities used in fraud schemes.", detail: "{{count}} vendors with PO Box or minimal address details.", impact: "Fictitious vendor fraud risk", recommendation: "Verify physical address and company registration for all PO Box suppliers — remove unverified vendors from the master file." },
  { id: "CF_026", layer: 7, name: "APPROVAL_OVERRIDE_INDICATORS", fileType: "trial_balance", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["override","bypass","approved by exception","urgent","emergency","authorised verbally","emergency approval"], nameField: ["account_name","description"], message: "{{count}} approval override or emergency authorisation entries", description: "Approvals granted by exception or override bypass normal controls and require post-hoc review.", detail: "{{count}} entries with override/exception approval indicators.", impact: "Control bypass — subject to management review", recommendation: "Review all override approvals — confirm they were genuinely necessary and are retrospectively approved by the board." },
  { id: "CF_027", layer: 7, name: "CHARITABLE_DONATION_LARGE", fileType: "trial_balance", category: "controls", severity: "low", confidence: "medium", type: "keyword", field: ["account_name","description"], keywords: ["donation","charity donation","charitable contribution","gift aid"], nameField: ["account_name"], message: "{{count}} charitable donation entries — confirm board approval", description: "Large charitable donations require board approval and may have Gift Aid implications.", detail: "{{count}} charitable donation entries found.", impact: "Board approval and Gift Aid review required", recommendation: "Confirm all charitable donations have board approval — register for Gift Aid where eligible." },
  { id: "CF_028", layer: 7, name: "POLITICAL_DONATION_PROHIBITED", fileType: "trial_balance", category: "controls", severity: "high", confidence: "medium", type: "keyword", field: ["account_name","description"], keywords: ["political donation","political party","political contribution","campaign donation","election"], nameField: ["account_name"], message: "Political donation indicators detected — Companies Act review required", description: "Donations to political parties require shareholder approval under the Companies Act 2006.", detail: "Political donation indicators found.", impact: "Shareholder approval required — legal compliance risk", recommendation: "Obtain shareholder approval for all political donations as required by the Companies Act 2006.", evidenceStrength: "advisory" },
  { id: "CF_029", layer: 7, name: "BRIBERY_ACT_RISK_INDICATORS", fileType: "trial_balance", category: "controls", severity: "critical", confidence: "low", type: "keyword", field: ["description","account_name"], keywords: ["facilitation payment","facilitating payment","agent payment","commission agent","kickback","inducement"], nameField: ["account_name","description"], message: "Bribery Act risk indicators detected — legal review required", description: "Facilitating payments, kickbacks or unusual agent commissions may constitute bribery under the UK Bribery Act 2010.", detail: "Bribery Act risk indicators found in the financial records.", impact: "Criminal liability under UK Bribery Act 2010", recommendation: "Refer immediately to legal counsel — report to Nominated Officer if suspicion of bribery is confirmed.", evidenceStrength: "indicator" },
  { id: "CF_030", layer: 7, name: "AML_STRUCTURING_INDICATORS", fileType: "any", category: "controls", severity: "critical", confidence: "low", type: "keyword", field: ["description","amount"], keywords: ["structuring","smurfing","cash below threshold","9999","9,999","avoid reporting"], nameField: ["account_name","description"], message: "Anti-money laundering structuring indicators detected", description: "Transactions structured just below reporting thresholds to avoid AML monitoring are a serious criminal offence.", detail: "AML structuring indicators found.", impact: "Criminal liability — mandatory SAR reporting obligation", recommendation: "Report to MLRO immediately — file Suspicious Activity Report (SAR) with NCA if suspicion is confirmed.", evidenceStrength: "advisory" },
  { id: "CF_031", layer: 7, name: "TRAVEL_EXPENSE_HIGH_VOLUME", fileType: "trial_balance", category: "controls", severity: "low", confidence: "low", type: "keyword", field: ["account_name"], keywords: ["travel expense","airline","hotel","accommodation","taxi","mileage","rail","train"], nameField: ["account_name"], message: "Travel expense accounts detected — volume and policy review", description: "High travel expense volumes should be reviewed against company policy and compared to prior periods.", detail: "Travel expense accounts found.", impact: "Travel expense policy compliance review", recommendation: "Review travel expenses against policy — confirm all receipts are held and policy limits are respected.", evidenceStrength: "indicator" },
  { id: "CF_032", layer: 7, name: "ENTERTAINMENT_POLICY_BREACH", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["account_name","description"], keywords: ["client entertainment","staff entertainment","business entertainment","entertainment expense","hospitality expense"], nameField: ["account_name"], message: "Entertainment expenses detected — review against policy and HMRC limits", description: "Entertainment expenses should be within company policy limits and correctly coded for VAT purposes.", detail: "Entertainment expense account(s) found.", impact: "Policy breach and VAT input tax recovery risk", recommendation: "Review entertainment expenses against company policy — ensure VAT input tax is not incorrectly claimed.", evidenceStrength: "indicator" },
  { id: "CF_033", layer: 7, name: "DIRECTOR_RELATED_TRANSACTION", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["description","account_name","narration"], keywords: ["director","DLA","directors current","shareholder loan","board member","executive"], nameField: ["account_name","description"], message: "{{count}} director or shareholder-related transactions — disclosure check", description: "All transactions with directors and shareholders must be disclosed under Companies Act 2006 and accounting standards.", detail: "{{count}} director/shareholder-related transaction references found.", impact: "Disclosure and related party requirements apply", recommendation: "Disclose all director-related transactions in the financial statements — confirm arm's length basis." },
  { id: "CF_034", layer: 7, name: "VENDOR_MASTER_DUPLICATE_BANK", fileType: "aged_creditors", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["supplier"], keywords: ["duplicate","copy","dup","(2)","(copy)","_old","_new","v2"], nameField: ["supplier","vendor"], message: "Duplicate vendor master entry indicators — risk of payment to wrong account", description: "Vendor master duplicates with version suffixes indicate vendors have been duplicated, increasing payment error risk.", detail: "Vendor name duplication indicators found.", impact: "Payment to incorrect bank account risk", recommendation: "Clean up vendor master — remove duplicates and ensure single active record per supplier.", evidenceStrength: "indicator" },
  { id: "CF_035", layer: 7, name: "PAYROLL_GHOST_EMPLOYEE_INDICATORS", fileType: "trial_balance", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["ghost","terminated","leaver","left company","deceased","no longer employed"], nameField: ["account_name","description"], message: "Ghost employee risk indicators in payroll entries", description: "Payroll entries for terminated or non-existent employees represent one of the most common internal fraud schemes.", detail: "Ghost employee indicators found in payroll-related entries.", impact: "Payroll fraud risk", recommendation: "Reconcile payroll to HR records — confirm all payees are active employees with valid employment records.", evidenceStrength: "advisory" },
  { id: "CF_036", layer: 7, name: "INVENTORY_SHRINKAGE_UNUSUAL", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["account_name","description"], keywords: ["shrinkage","wastage","spoilage","write-off","theft","loss adjustment"], nameField: ["account_name"], message: "Inventory shrinkage or wastage entries detected — review for unusual patterns", description: "High levels of inventory shrinkage may mask theft or inventory fraud.", detail: "Inventory shrinkage/wastage entries found.", impact: "Inventory theft risk — review controls", recommendation: "Review shrinkage levels against industry norms — strengthen goods-in/goods-out controls if materially high.", evidenceStrength: "advisory" },
  { id: "CF_037", layer: 7, name: "MANAGEMENT_OVERRIDE_JOURNAL", fileType: "trial_balance", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["posted_by","created_by","user"], keywords: ["CFO","CEO","MD","Director","Managing Director","FD"], nameField: ["account_name","description"], message: "Senior management journal entries — independent review required", description: "Journal entries posted directly by CFOs, CEOs or directors without countersignature are a fraud risk (COSO framework).", detail: "Senior management user postings detected.", impact: "Management override risk — audit committee should review", recommendation: "Report senior management journal entries to the audit committee — implement countersignature requirements.", evidenceStrength: "indicator" },
  { id: "CF_038", layer: 7, name: "FICTITIOUS_REVENUE_INDICATORS", fileType: "profit_loss", category: "controls", severity: "critical", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["fictitious","fake","inflated","dummy","artificial","mock","test"], nameField: ["account_name","description"], message: "Fictitious or artificial revenue indicators detected", description: "Revenue entries with fictitious or artificial indicators may represent fraudulent inflation of income.", detail: "Fictitious revenue indicators found in the P&L.", impact: "Revenue fraud — financial statements may be materially misstated", recommendation: "Immediately escalate to external auditors and audit committee — investigate all flagged entries.", evidenceStrength: "advisory" },
  { id: "CF_039", layer: 7, name: "UNUSUAL_BANK_TRANSFER", fileType: "trial_balance", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["internal transfer","interbank","between accounts","sweep","cash sweep"], nameField: ["account_name"], message: "{{count}} unusual interbank transfer entries — review for authorisation", description: "Interbank transfers between company accounts should be supported by treasury instructions and authorisation.", detail: "{{count}} interbank or cash sweep entries found.", impact: "Unauthorised fund movement risk", recommendation: "Review all interbank transfers — confirm authorisation from treasury or CFO." },
  { id: "CF_040", layer: 7, name: "THRESHOLD_CLUSTERING_1000", fileType: "any", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["amount"], keywords: ["999","998","997","995","990"], nameField: ["description","account_name"], message: "Cluster of amounts just below £1,000 — approval threshold avoidance suspected", description: "Multiple transactions clustered just below £1,000 may indicate deliberate avoidance of the £1,000 approval limit.", detail: "Transactions just below the £1,000 approval limit detected.", impact: "Approval control bypass suspected", recommendation: "Review all sub-£1,000 transactions — implement cumulative controls to prevent threshold avoidance.", evidenceStrength: "indicator" },
  { id: "CF_041", layer: 7, name: "THRESHOLD_CLUSTERING_5000", fileType: "any", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["amount"], keywords: ["4999","4998","4995","4990","4,999","4,998"], nameField: ["description","account_name"], message: "Cluster of amounts just below £5,000 — approval threshold avoidance suspected", description: "Multiple transactions clustered just below £5,000 indicate deliberate approval limit avoidance.", detail: "Transactions just below the £5,000 threshold detected.", impact: "Approval control bypass suspected", recommendation: "Implement cumulative approval controls for transactions from the same supplier over any 7-day period.", evidenceStrength: "advisory" },
  { id: "CF_042", layer: 7, name: "THRESHOLD_CLUSTERING_10000", fileType: "any", category: "controls", severity: "high", confidence: "medium", type: "keyword", field: ["amount"], keywords: ["9999","9998","9995","9,999","9,998","9990"], nameField: ["description","account_name"], message: "Cluster of amounts just below £10,000 — AML and approval threshold concern", description: "Transactions clustered just below £10,000 trigger both approval limit concerns and AML structuring risk.", detail: "Sub-£10,000 threshold clustering detected.", impact: "AML structuring risk and approval bypass", recommendation: "Report to MLRO for AML assessment — implement cumulative approval controls.", evidenceStrength: "advisory" },
  { id: "CF_043", layer: 7, name: "UNRECONCILED_BANK_ITEMS", fileType: "trial_balance", category: "controls", severity: "high", confidence: "medium", type: "keyword", field: ["account_name","description"], keywords: ["outstanding","unreconciled","timing difference","in transit","uncleared deposit"], nameField: ["account_name"], message: "Unreconciled bank items detected — bank reconciliation may be incomplete", description: "Long-outstanding bank reconciling items indicate the bank reconciliation has not been fully cleared.", detail: "Unreconciled bank item indicators found.", impact: "Bank reconciliation integrity at risk", recommendation: "Complete bank reconciliation — clear all outstanding items or obtain management approval for long-outstanding items.", evidenceStrength: "advisory" },
  { id: "CF_044", layer: 7, name: "JOURNAL_POSTED_AFTER_AUDIT", fileType: "trial_balance", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["post-audit","after audit","audit entry","signed off","finalised"], nameField: ["account_name","description"], message: "Post-audit journal entries detected — accounts may have been amended after sign-off", description: "Journals posted after audit sign-off indicate accounts were amended after the audit was completed.", detail: "Post-audit journal indicators found.", impact: "Accounts may have been amended without auditor knowledge", recommendation: "Escalate to external auditors immediately — any post-sign-off amendments may invalidate the audit report.", evidenceStrength: "advisory" },
  { id: "CF_045", layer: 7, name: "REFUND_EXCEEDS_ORIGINAL", fileType: "aged_debtors", category: "controls", severity: "high", confidence: "medium", type: "sign", field: ["amount","balance"], keywords: ["negative"], threshold: 50000, nameField: ["customer","account_name"], message: "Large refund or credit balance in AR — verify against original invoice", description: "Credit balances exceeding the original invoice amount may indicate over-refunding, which is a common fraud vector.", detail: "Large credit balances detected in the AR ledger: {{total}}", impact: "Over-refund fraud risk", recommendation: "Verify all large AR credit balances — confirm credit note or refund matches the original invoice amount." },
  { id: "CF_046", layer: 7, name: "FIXED_ASSET_DISPOSAL_REVIEW", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "medium", type: "keyword", field: ["account_name","description"], keywords: ["disposal","sold","disposed","derecognised","written off asset","asset sale"], nameField: ["account_name"], message: "Fixed asset disposal entries — confirm proceeds received and gain/loss correct", description: "Asset disposals must be authorised, proceeds collected and gain/loss calculated correctly.", detail: "{{count}} asset disposal entries found.", impact: "Disposal proceeds may not have been received", recommendation: "Confirm asset disposal proceeds have been received — verify gain/loss calculation and update fixed asset register." },
  { id: "CF_047", layer: 7, name: "CASH_RECEIPT_MISAPPROPRIATION", fileType: "trial_balance", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["cash received","cash receipt","deposit","till receipt","cash in"], nameField: ["account_name"], message: "Cash receipt entries — confirm all receipts are properly banked", description: "Cash receipt misappropriation (lapping) is common where cash is received and not immediately banked.", detail: "Cash receipt entries found — verify banking procedures.", impact: "Cash receipt fraud risk", recommendation: "Confirm all cash receipts are banked the same or next day — reconcile till receipts to banking slips.", evidenceStrength: "indicator" },
  { id: "CF_048", layer: 7, name: "SHARE_ISSUANCE_UNAUTHORISED", fileType: "balance_sheet", category: "controls", severity: "critical", confidence: "low", type: "keyword", field: ["account_name","description"], keywords: ["share issue","new shares","issued share capital","bonus issue","rights issue","share allotment"], nameField: ["account_name"], message: "New share issuance detected — confirm shareholder approval obtained", description: "New share issuances require shareholder approval and must be registered at Companies House.", detail: "Share issuance indicators found.", impact: "Unauthorised share dilution risk", recommendation: "Confirm board and shareholder approval exists — file SH01 at Companies House.", evidenceStrength: "advisory" },
  { id: "CF_049", layer: 7, name: "DATA_MANIPULATION_INDICATORS", fileType: "any", category: "controls", severity: "critical", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["deleted","removed","hidden","suppressed","manipulated","adjusted to target","massaged"], nameField: ["account_name","description"], message: "Data manipulation indicators detected in journal narrations", description: "References to deleted, hidden or manipulated data are serious red flags for financial fraud or misstatement.", detail: "Data manipulation indicators found.", impact: "Financial statement fraud risk", recommendation: "Immediately escalate to external auditors and board — preserve all evidence of potential data manipulation.", evidenceStrength: "advisory" },
  { id: "CF_050", layer: 7, name: "YEAR_END_INCOME_ACCELERATION", fileType: "profit_loss", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["bring forward","advance recognition","pull in","pre-year end","before year end","recognise early"], nameField: ["account_name","description"], message: "Year-end income acceleration indicators detected", description: "Revenue recognition in advance of performance obligations being met is a common form of financial statement fraud.", detail: "Income acceleration indicators found near year-end.", impact: "Revenue misstatement risk", recommendation: "Review all year-end revenue entries — confirm performance obligations were met before revenue was recognised.", evidenceStrength: "advisory" },
  { id: "CF_051", layer: 7, name: "VENDOR_CONCENTRATION_RISK", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "medium", type: "threshold", field: ["amount","balance"], comparator: "gt", threshold: 200000, nameField: ["supplier","vendor"], message: "{{count}} suppliers with very high individual balances — concentration risk", description: "Excessive concentration of payables with a small number of suppliers creates supply chain and financial risk.", detail: "{{count}} suppliers with balances over £200,000: {{names}}", impact: "Supply chain concentration risk", recommendation: "Diversify supplier base — ensure contingency plans exist for critical single-source suppliers." },
  { id: "CF_052", layer: 7, name: "INTERCO_UNUSUAL_BALANCE", fileType: "trial_balance", category: "controls", severity: "high", confidence: "medium", type: "keyword", field: ["account_name"], keywords: ["intercompany","intra group","due from","due to"], mustExist: true, nameField: ["account_name"], message: "Intercompany balance requires counterpart confirmation", description: "Unconfirmed intercompany balances are a significant control weakness and may indicate manipulation.", detail: "Intercompany accounts detected — counterpart confirmation required.", impact: "Intercompany reconciliation gap", recommendation: "Obtain formal written confirmation of intercompany balances from all counterpart entities.", evidenceStrength: "indicator" },
  { id: "CF_053", layer: 7, name: "REFUND_TO_DIFFERENT_PARTY", fileType: "aged_debtors", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["description","narration"], keywords: ["refund to","refund payable to","credit to different","paid to third party"], nameField: ["customer","account_name"], message: "Refund or credit to a different party from the original customer", description: "Redirecting refunds to parties different from the original customer is a fraud vector.", detail: "Refund-to-different-party indicators found.", impact: "Refund fraud risk", recommendation: "Confirm all refunds are returned to the original payment method and customer — escalate any redirections.", evidenceStrength: "advisory" },
  { id: "CF_054", layer: 7, name: "LARGE_MANUAL_ADJUSTMENT", fileType: "trial_balance", category: "controls", severity: "high", confidence: "medium", type: "threshold", field: ["balance","amount"], comparator: "gt", threshold: 100000, nameField: ["account_name","description"], message: "{{count}} large manual adjustment entries (>£100,000)", description: "Manual adjustments above £100,000 are material and require independent review and documented justification.", detail: "{{count}} manual adjustment entries exceeding £100,000.", impact: "Material adjustment requires independent review", recommendation: "Obtain board or audit committee approval for all manual adjustments over £100,000 — document calculation basis." },
  { id: "CF_055", layer: 7, name: "CHARITABLE_TRUST_SORP_CHECK", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["account_name","description"], keywords: ["restricted fund","unrestricted fund","endowment","charity fund","SORP","charitable purpose"], nameField: ["account_name"], message: "Charity fund accounting indicators — SORP compliance check", description: "Charities must account for restricted, unrestricted and endowment funds separately under the Charities SORP.", detail: "Charity fund accounting indicators detected.", impact: "Charities SORP compliance required", recommendation: "Confirm fund accounting complies with the Charities SORP — report restricted and unrestricted funds separately.", evidenceStrength: "advisory" },
  { id: "CF_056", layer: 7, name: "EXPENSE_RATIO_CHARITY", fileType: "profit_loss", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["account_name"], keywords: ["charitable activity","charitable expenditure","fundraising cost","support cost","governance"], nameField: ["account_name"], message: "Charity expenditure ratios — confirm within Charity Commission guidance", description: "Charities should maximise spending on charitable purposes — very high governance or support costs may raise regulatory concerns.", detail: "Charity expenditure categories detected.", impact: "Charity Commission scrutiny risk if overhead ratios are very high", recommendation: "Review expenditure ratios — ensure charitable activity expenditure is the dominant cost category.", evidenceStrength: "advisory" },
  { id: "CF_057", layer: 7, name: "CYBER_INCIDENT_PROVISION", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["description","account_name"], keywords: ["cyber","data breach","ransomware","hacking incident","cybersecurity incident"], nameField: ["account_name"], message: "Cyber incident provision or cost detected", description: "Cyber incident costs should be properly classified and any regulatory fines or remediation costs disclosed.", detail: "Cyber incident related entries found.", impact: "Disclosure and regulatory reporting may be required", recommendation: "Disclose cyber incident costs in the financial statements — report to ICO if personal data was breached.", evidenceStrength: "advisory" },
  { id: "CF_058", layer: 7, name: "WHISTLEBLOWER_RELATED", fileType: "trial_balance", category: "controls", severity: "high", confidence: "low", type: "keyword", field: ["description","account_name"], keywords: ["whistleblower","protected disclosure","concern raised","internal audit finding","fraud investigation"], nameField: ["account_name"], message: "Whistleblower or internal investigation entries detected", description: "Entries relating to whistleblower disclosures or fraud investigations must be handled carefully and disclosed where material.", detail: "Whistleblower/investigation related entries found.", impact: "Legal and disclosure obligations may apply", recommendation: "Ensure proper handling of whistleblower disclosures — consult legal counsel and consider disclosure obligations.", evidenceStrength: "advisory" },
  { id: "CF_059", layer: 7, name: "SANCTIONS_COMPLIANCE_CHECK", fileType: "aged_creditors", category: "controls", severity: "critical", confidence: "low", type: "keyword", field: ["supplier","description"], keywords: ["Russia","Iran","North Korea","Syria","Belarus","Cuba","Myanmar","Venezuela","OFAC","OFSI","sanctioned"], nameField: ["supplier","vendor"], message: "Possible sanctioned country or entity in AP — OFSI compliance check required", description: "Payments to or from sanctioned countries or entities may violate OFSI or OFAC sanctions regulations.", detail: "Sanctioned country/entity indicators found in AP.", impact: "Criminal liability under UK/US sanctions law", recommendation: "Immediately suspend any payments to flagged parties — check OFSI consolidated list and seek legal advice.", evidenceStrength: "advisory" },
  { id: "CF_060", layer: 7, name: "MODERN_SLAVERY_SUPPLY_CHAIN", fileType: "aged_creditors", category: "controls", severity: "medium", confidence: "low", type: "keyword", field: ["supplier","description"], keywords: ["overseas labour","cheap labour","offshore manufacture","third world supplier","developing country manufacture"], nameField: ["supplier","vendor"], message: "Supply chain risk indicators — Modern Slavery Act check", description: "Businesses with turnover over £36M must publish an annual Modern Slavery Act statement covering their supply chain.", detail: "Supply chain risk indicators found in AP.", impact: "Modern Slavery Act compliance obligation", recommendation: "Review supply chain for modern slavery risks — publish annual Modern Slavery Act statement if turnover exceeds £36M.", evidenceStrength: "advisory" },
];

const deterministicControls = new Set([
  "CF_005",
  "CF_006",
  "CF_016",
  "CF_021",
  "CF_022",
  "CF_045",
  "CF_054",
]);

const controlIndicators = new Set([
  "CF_001",
  "CF_002",
  "CF_003",
  "CF_004",
  "CF_007",
  "CF_008",
  "CF_009",
  "CF_010",
  "CF_011",
  "CF_015",
  "CF_017",
  "CF_020",
  "CF_023",
  "CF_025",
  "CF_026",
  "CF_028",
  "CF_030",
  "CF_031",
  "CF_032",
  "CF_033",
  "CF_034",
  "CF_035",
  "CF_036",
  "CF_037",
  "CF_039",
  "CF_040",
  "CF_046",
  "CF_047",
  "CF_051",
  "CF_052",
]);

const complianceReminders = new Set([
  "CF_012",
  "CF_013",
  "CF_014",
  "CF_018",
  "CF_019",
  "CF_024",
  "CF_027",
  "CF_029",
  "CF_038",
  "CF_041",
  "CF_042",
  "CF_043",
  "CF_044",
  "CF_048",
  "CF_049",
  "CF_050",
  "CF_053",
  "CF_055",
  "CF_056",
  "CF_057",
  "CF_058",
  "CF_059",
  "CF_060",
]);

function normaliseControlsRule(rule: AssuranceRule): AssuranceRule {
  if (deterministicControls.has(rule.id)) {
    return { ...rule, evidenceStrength: "deterministic" };
  }

  if (controlIndicators.has(rule.id)) {
    return { ...rule, evidenceStrength: "indicator" };
  }

  if (complianceReminders.has(rule.id)) {
    return {
      ...rule,
      severity: "low",
      confidence: "low",
      evidenceStrength: "advisory",
      message: rule.message.startsWith("Review reminder:") ? rule.message : `Review reminder: ${rule.message}`,
      impact: rule.impact?.startsWith("Review reminder") ? rule.impact : `Review reminder — ${rule.impact ?? "consider disclosure or compliance implications"}`,
    };
  }

  return { ...rule, evidenceStrength: rule.evidenceStrength ?? "indicator" };
}

export const controlsFraudRules: AssuranceRule[] = controlsFraudRulesRaw.map(normaliseControlsRule);
