import type { AssuranceRule } from "@/lib/types/rule";

// Layer 1 — Data Integrity Engine: 50 rules
// Purpose: Can we trust the uploaded data?

export const dataIntegrityRules: AssuranceRule[] = [
  // ── Trial Balance ─────────────────────────────────────────────────────────
  { id: "DI_001", layer: 1, name: "TB_BLANK_ACCOUNT_NAME", fileType: "trial_balance", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["account_name"], percentage: 5, message: "{{count}} rows have no account name in the trial balance", description: "Blank account names prevent proper account classification and audit trail validation.", detail: "{{count}} rows ({{pct}}) in the trial balance have no account name.", impact: "Data quality gap — accounts cannot be categorised", recommendation: "Populate all account name fields before export." },
  { id: "DI_002", layer: 1, name: "TB_BLANK_ACCOUNT_CODE", fileType: "trial_balance", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["account_code"], percentage: 5, message: "{{count}} trial balance rows have no account code", description: "Missing account codes make it impossible to map transactions to the chart of accounts.", detail: "{{count}} rows are missing account codes.", impact: "Mapping failure — analysis may be incomplete", recommendation: "Export trial balance with account codes populated." },
  { id: "DI_003", layer: 1, name: "TB_FUTURE_DATED_JOURNAL", fileType: "trial_balance", category: "controls", severity: "medium", confidence: "high", type: "aging", dateField: ["posting_date","entry_date","journal_date"], days: -36500, message: "Future-dated journal entries detected", description: "Journals with a future date may indicate data entry errors or system date misconfigurations.", detail: "{{count}} journal entries are dated after today.", impact: "Data integrity risk", recommendation: "Review and correct future-dated entries." },
  { id: "DI_004", layer: 1, name: "TB_SUSPENSE_ACCOUNT", fileType: "trial_balance", category: "controls", severity: "high", confidence: "high", type: "existence", field: ["account_name"], keywords: ["suspense","clearing","holding","temp","query","unallocated","tbc"], mustExist: true, threshold: 1, message: "Suspense or clearing account balance outstanding", description: "Suspense accounts must be cleared before period-end sign-off.", detail: "Account(s) named {{names}} have an outstanding balance.", impact: "Sign-off blocker — suspense must be allocated", recommendation: "Allocate all suspense balances to correct nominal codes before sign-off." },
  { id: "DI_005", layer: 1, name: "TB_MISSING_RETAINED_EARNINGS", fileType: "trial_balance", category: "data_quality", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["retained earnings","profit and loss account","accumulated surplus","accumulated deficit","p&l reserve"], mustExist: false, message: "No retained earnings account found in the trial balance", description: "A trial balance without a retained earnings or P&L reserve account may be incomplete or incorrectly structured.", detail: "No row found matching retained earnings in the account name column.", impact: "Completeness concern — balance sheet may be incomplete", recommendation: "Confirm retained earnings account is present and correctly labelled.", evidenceStrength: "indicator" },
  { id: "DI_006", layer: 1, name: "TB_MISSING_VAT_CONTROL", fileType: "trial_balance", category: "data_quality", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["vat control","vat liability","vat output","tax control","vat payable"], mustExist: false, message: "No VAT control account found in the trial balance", description: "A missing VAT control account prevents reconciliation of the VAT report to the ledger.", detail: "No VAT control account found — VAT reconciliation cannot be performed.", impact: "VAT reconciliation gap", recommendation: "Confirm VAT control account is included in the TB export.", evidenceStrength: "indicator" },
  { id: "DI_007", layer: 1, name: "TB_MISSING_BANK_ACCOUNT", fileType: "trial_balance", category: "data_quality", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["bank","cash at bank","current account","bank account","cash and bank"], mustExist: false, message: "No bank or cash account found in the trial balance", description: "A missing bank account makes cash position and bank reconciliation checks impossible.", detail: "No bank or cash account row found in the TB.", impact: "Cash position cannot be verified", recommendation: "Confirm bank accounts are included in the TB export.", evidenceStrength: "indicator" },
  { id: "DI_008", layer: 1, name: "TB_NEGATIVE_DEBTORS_CONTROL", fileType: "trial_balance", category: "month_end", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["trade debtor","accounts receivable","debtor control","receivable"], mustExist: false, message: "No trade debtors control account found in the trial balance", description: "Without a debtors control account, AR cannot be reconciled to the TB.", detail: "No debtors control account detected in the trial balance.", impact: "AR reconciliation cannot be performed", recommendation: "Include trade debtors control account in TB export.", evidenceStrength: "indicator" },
  { id: "DI_009", layer: 1, name: "TB_MISSING_CREDITORS_CONTROL", fileType: "trial_balance", category: "month_end", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["trade creditor","accounts payable","creditor control","payable"], mustExist: false, message: "No trade creditors control account found in the trial balance", description: "Without a creditors control account, AP cannot be reconciled to the TB.", detail: "No creditors control account detected.", impact: "AP reconciliation cannot be performed", recommendation: "Include trade creditors control account in TB export.", evidenceStrength: "indicator" },
  { id: "DI_010", layer: 1, name: "TB_ROUND_JOURNAL_SPIKE", fileType: "trial_balance", category: "controls", severity: "low", confidence: "low", type: "percentage", field: ["balance","amount","debit","credit"], keywords: [], percentage: 25, message: "High proportion of round-number amounts in the trial balance", description: "When more than 25% of balances are exact multiples of £1,000, it may indicate estimated rather than actual figures.", detail: "{{count}} of {{total}} balances ({{pct}}) are round-number multiples of £1,000.", impact: "Estimation risk — verify amounts are actual", recommendation: "Confirm round-number entries represent actual invoiced amounts." },

  // ── Aged Debtors ─────────────────────────────────────────────────────────
  { id: "DI_011", layer: 1, name: "AR_BLANK_CUSTOMER_NAME", fileType: "aged_debtors", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["customer"], percentage: 5, message: "{{count}} AR rows have no customer name", description: "Missing customer names prevent collections follow-up and audit trail completeness.", detail: "{{count}} aged debtor rows ({{pct}}) are missing a customer name.", impact: "Collections cannot be initiated for unnamed debtors", recommendation: "Populate customer names in the accounts receivable ledger." },
  { id: "DI_012", layer: 1, name: "AR_BLANK_INVOICE_DATE", fileType: "aged_debtors", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["date"], percentage: 10, message: "{{count}} AR rows have no invoice date", description: "Missing invoice dates prevent aging analysis and collection prioritisation.", detail: "{{count}} aged debtor rows are missing an invoice date.", impact: "Aging analysis is incomplete", recommendation: "Export aged debtors with invoice date column populated." },
  { id: "DI_013", layer: 1, name: "AR_FUTURE_DATED_INVOICE", fileType: "aged_debtors", category: "data_quality", severity: "medium", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: -36500, message: "Future-dated AR invoices detected", description: "Invoices dated in the future indicate data entry errors or pre-posting of invoices.", detail: "{{count}} invoices are dated after today.", impact: "Aging calculations are distorted", recommendation: "Review and correct future-dated invoice entries." },
  { id: "DI_014", layer: 1, name: "AR_DUPLICATE_INVOICE_REF", fileType: "aged_debtors", category: "ar", severity: "high", confidence: "high", type: "keyword", field: ["invoice_ref","reference","ref"], keywords: ["INV","inv"], message: "Possible duplicate invoice references in aged debtors", description: "Duplicate invoice references may indicate double-billing or billing errors.", detail: "Multiple rows share invoice reference patterns.", impact: "Double-billing risk", recommendation: "Review duplicate invoice references with the billing team.", evidenceStrength: "indicator" },
  { id: "DI_015", layer: 1, name: "AR_IMPLAUSIBLE_AMOUNT", fileType: "aged_debtors", category: "data_quality", severity: "medium", confidence: "medium", type: "threshold", field: ["amount","balance","outstanding"], comparator: "gt", threshold: 10000000, message: "Implausibly large debtor balance (>£10M on a single row)", description: "A single AR balance over £10M may indicate a decimal point error or data parsing failure.", detail: "{{count}} rows have amounts exceeding £10,000,000.", impact: "Data parsing error likely", recommendation: "Verify and correct implausibly large balances." },

  // ── Aged Creditors ────────────────────────────────────────────────────────
  { id: "DI_016", layer: 1, name: "AP_BLANK_SUPPLIER_NAME", fileType: "aged_creditors", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["supplier"], percentage: 5, message: "{{count}} AP rows have no supplier name", description: "Missing supplier names prevent payment processing and audit trail completeness.", detail: "{{count}} aged creditor rows ({{pct}}) are missing a supplier name.", impact: "Payment and audit trail gaps", recommendation: "Populate supplier names in the accounts payable ledger." },
  { id: "DI_017", layer: 1, name: "AP_BLANK_INVOICE_REF", fileType: "aged_creditors", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["invoice_ref"], percentage: 10, message: "{{count}} AP rows have no invoice reference", description: "Missing invoice references prevent three-way matching and duplicate payment detection.", detail: "{{count}} creditor rows ({{pct}}) have no invoice reference.", impact: "Duplicate payment risk increases", recommendation: "Include invoice reference in AP export for full analysis." },
  { id: "DI_018", layer: 1, name: "AP_BLANK_INVOICE_DATE", fileType: "aged_creditors", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["date"], percentage: 10, message: "{{count}} AP rows have no invoice date", description: "Missing invoice dates prevent aging analysis and payment term compliance checks.", detail: "{{count}} creditor rows are missing an invoice date.", impact: "Aging and payment term analysis is incomplete", recommendation: "Export aged creditors with invoice date populated." },
  { id: "DI_019", layer: 1, name: "AP_FUTURE_DATED_INVOICE", fileType: "aged_creditors", category: "data_quality", severity: "medium", confidence: "high", type: "aging", dateField: ["date","invoice_date"], days: -36500, message: "Future-dated AP invoices detected", description: "Creditor invoices dated in the future indicate pre-posting or system date errors.", detail: "{{count}} AP invoices are dated after today.", impact: "AP aging is distorted by future dates", recommendation: "Review and correct future-dated creditor entries." },
  { id: "DI_020", layer: 1, name: "AP_IMPLAUSIBLE_AMOUNT", fileType: "aged_creditors", category: "data_quality", severity: "medium", confidence: "medium", type: "threshold", field: ["amount","balance"], comparator: "gt", threshold: 5000000, message: "Implausibly large creditor invoice (>£5M single row)", description: "A single AP amount over £5M may indicate a formatting or parsing error.", detail: "{{count}} AP rows exceed £5,000,000 per invoice.", impact: "Data integrity risk", recommendation: "Verify and correct implausibly large AP invoice amounts." },

  // ── VAT Report ───────────────────────────────────────────────────────────
  { id: "DI_021", layer: 1, name: "VAT_BLANK_VAT_CODE", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "percentage", field: ["vat_code"], percentage: 5, message: "{{count}} VAT transactions have no VAT code", description: "Transactions without VAT codes cannot be included in the VAT return correctly.", detail: "{{count}} VAT rows ({{pct}}) have no VAT/tax code.", impact: "VAT return may be incomplete", recommendation: "Assign VAT codes to all transactions before return submission." },
  { id: "DI_022", layer: 1, name: "VAT_BLANK_SUPPLIER", fileType: "vat_report", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["supplier","customer","account_name"], percentage: 10, message: "{{count}} VAT transactions have no supplier or customer name", description: "Missing party names on VAT transactions make HMRC enquiry responses difficult.", detail: "{{count}} VAT rows are missing a supplier or customer name.", impact: "HMRC enquiry risk", recommendation: "Include supplier/customer names in all VAT transactions." },
  { id: "DI_023", layer: 1, name: "VAT_IMPLAUSIBLE_AMOUNT", fileType: "vat_report", category: "data_quality", severity: "medium", confidence: "medium", type: "threshold", field: ["vat_amount","amount"], comparator: "gt", threshold: 1000000, message: "Implausibly large VAT amount (>£1M on single transaction)", description: "A VAT amount exceeding £1M on a single transaction likely indicates a data error.", detail: "{{count}} VAT rows have amounts exceeding £1,000,000.", impact: "VAT return calculation error risk", recommendation: "Verify large VAT amounts before submission." },
  { id: "DI_024", layer: 1, name: "VAT_FUTURE_DATED", fileType: "vat_report", category: "data_quality", severity: "medium", confidence: "high", type: "aging", dateField: ["date","invoice_date","transaction_date"], days: -36500, message: "Future-dated VAT transactions detected", description: "Future-dated VAT transactions may be included in the wrong return period.", detail: "{{count}} VAT transactions are dated after today.", impact: "Wrong period inclusion risk", recommendation: "Review future-dated VAT transactions for correct period allocation." },

  // ── P&L ───────────────────────────────────────────────────────────────────
  { id: "DI_025", layer: 1, name: "PL_BLANK_ACCOUNT_NAME", fileType: "profit_loss", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["account_name"], percentage: 5, message: "{{count}} P&L rows have no account name", description: "Missing account names in the P&L prevent proper categorisation of income and expenses.", detail: "{{count}} P&L rows are missing an account name.", impact: "P&L analysis is incomplete", recommendation: "Populate all account names before exporting the P&L." },
  { id: "DI_026", layer: 1, name: "PL_MISSING_REVENUE", fileType: "profit_loss", category: "data_quality", severity: "high", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["revenue","turnover","sales","income"], mustExist: false, message: "No revenue or turnover account found in the P&L", description: "A P&L without any revenue row may be incomplete or incorrectly structured.", detail: "No row matching revenue, turnover, sales, or income was found.", impact: "P&L may be incomplete", recommendation: "Confirm revenue accounts are included in the P&L export.", evidenceStrength: "indicator" },
  { id: "DI_027", layer: 1, name: "PL_MISSING_COGS", fileType: "profit_loss", category: "data_quality", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["cost of sale","cogs","direct cost"], mustExist: false, message: "No cost of sales or COGS account found in the P&L", description: "Without a cost of sales row, gross margin cannot be calculated.", detail: "No COGS/direct costs row found in the P&L.", impact: "Gross margin analysis not possible", recommendation: "Include COGS/direct costs in the P&L export.", evidenceStrength: "indicator" },

  // ── Balance Sheet ─────────────────────────────────────────────────────────
  { id: "DI_028", layer: 1, name: "BS_BLANK_ACCOUNT", fileType: "balance_sheet", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["account_name"], percentage: 5, message: "{{count}} balance sheet rows have no account name", description: "Unnamed balance sheet accounts prevent proper asset/liability classification.", detail: "{{count}} BS rows are missing account names.", impact: "Balance sheet analysis is incomplete", recommendation: "Populate all account names before export." },
  { id: "DI_029", layer: 1, name: "BS_MISSING_EQUITY", fileType: "balance_sheet", category: "data_quality", severity: "high", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["equity","net asset","shareholders","capital and reserve","retained"], mustExist: false, message: "No equity or net assets section found in the balance sheet", description: "A balance sheet without an equity section is structurally incomplete.", detail: "No equity or net assets row detected in the balance sheet.", impact: "Balance sheet is structurally incomplete", recommendation: "Ensure equity section is included in the BS export.", evidenceStrength: "advisory" },
  { id: "DI_030", layer: 1, name: "BS_MISSING_CURRENT_ASSETS", fileType: "balance_sheet", category: "data_quality", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["current asset","debtor","cash","stock","prepayment","short-term asset"], mustExist: false, message: "No current assets found in the balance sheet", description: "A balance sheet without current assets may be missing debtors, cash or stock.", detail: "No current asset rows detected.", impact: "Liquidity analysis not possible", recommendation: "Include current asset accounts in the BS export.", evidenceStrength: "advisory" },

  // ── Cross-File ─────────────────────────────────────────────────────────────
  { id: "DI_031", layer: 1, name: "ANY_DUPLICATE_ROW", fileType: "any", category: "data_quality", severity: "medium", confidence: "high", type: "percentage", field: ["description","account_name"], keywords: [], percentage: 1, message: "Possible duplicate rows detected in {{file}}", description: "Rows appearing to be duplicates indicate import errors or double-counting.", detail: "{{count}} rows appear to be duplicates.", impact: "Data may be double-counted", recommendation: "Remove duplicate rows and investigate root cause." },
  { id: "DI_032", layer: 1, name: "ANY_CURRENCY_MISMATCH", fileType: "any", category: "data_quality", severity: "medium", confidence: "high", type: "keyword", field: ["currency"], keywords: ["USD","EUR","AED","CHF","JPY","AUD","CAD","SGD","HKD","INR"], message: "Foreign currency transactions in {{file}}", description: "Non-GBP transactions require FX translation at the correct rate.", detail: "{{count}} rows reference foreign currencies.", impact: "FX translation and revaluation required", recommendation: "Confirm FX rates and post any required revaluation entries." },

  // ── Additional DI rules ────────────────────────────────────────────────────
  { id: "DI_033", layer: 1, name: "TB_LARGE_SINGLE_BALANCE", fileType: "trial_balance", category: "data_quality", severity: "medium", confidence: "medium", type: "threshold", field: ["balance","amount"], comparator: "gt", threshold: 50000000, message: "Unusually large single account balance (>£50M)", description: "A single account balance over £50M warrants review — may indicate a data error or exceptional item.", detail: "{{count}} accounts exceed £50M balance.", impact: "Data integrity review required", recommendation: "Verify accounts with very large balances and confirm they represent genuine positions." },
  { id: "DI_034", layer: 1, name: "AR_BLANK_INVOICE_REF", fileType: "aged_debtors", category: "data_quality", severity: "low", confidence: "high", type: "percentage", field: ["invoice_ref"], percentage: 15, message: "{{count}} AR rows have no invoice reference", description: "Missing invoice references make it harder to match payments and resolve disputes.", detail: "{{count}} debtor rows are missing an invoice reference.", impact: "Collections and dispute resolution is harder", recommendation: "Include invoice references in the AR export." },
  { id: "DI_035", layer: 1, name: "VAT_ZERO_NET_AMOUNT", fileType: "vat_report", category: "data_quality", severity: "low", confidence: "medium", type: "threshold", field: ["net_amount","amount"], comparator: "eq", threshold: 0, message: "{{count}} VAT transactions have zero net amount", description: "VAT transactions with zero net amounts may be adjustment or error entries that need reviewing.", detail: "{{count}} VAT rows have zero net amount.", impact: "VAT return may include erroneous entries", recommendation: "Review zero-amount VAT entries and remove any that are in error." },
  { id: "DI_036", layer: 1, name: "AP_MISSING_DUE_DATE", fileType: "aged_creditors", category: "data_quality", severity: "low", confidence: "medium", type: "percentage", field: ["due_date"], percentage: 20, message: "{{count}} AP rows have no due date", description: "Missing due dates prevent payment term analysis and overdue detection.", detail: "{{count}} creditor rows ({{pct}}) have no due date.", impact: "Payment term compliance analysis not possible", recommendation: "Include due date in the AP export." },
  { id: "DI_037", layer: 1, name: "TB_ORPHAN_LARGE_BALANCE", fileType: "trial_balance", category: "data_quality", severity: "medium", confidence: "low", type: "keyword", field: ["account_name"], keywords: ["other","miscellaneous","misc","general","sundry"], message: "Material 'miscellaneous' or 'other' account balances detected", description: "Large balances in catch-all accounts like 'Other' or 'Sundry' may mask unallocated items.", detail: "{{count}} miscellaneous accounts found with balances.", impact: "Unallocated items may be hidden in catch-all accounts", recommendation: "Reclassify miscellaneous account balances to proper nominal codes." },
  { id: "DI_038", layer: 1, name: "ANY_IMPLAUSIBLE_DATE", fileType: "any", category: "data_quality", severity: "medium", confidence: "medium", type: "keyword", field: ["date","invoice_date"], keywords: ["1900","1901","1970","2099","2100"], message: "Implausible dates detected (year 1900 or 2099)", description: "Dates in the far past or future indicate system default dates or data corruption.", detail: "{{count}} rows have implausible date values.", impact: "Date-based analysis will be distorted", recommendation: "Correct implausible date values in the source system." },
  { id: "DI_039", layer: 1, name: "TB_ZERO_BALANCE_ACCOUNTS", fileType: "trial_balance", category: "data_quality", severity: "low", confidence: "high", type: "threshold", field: ["balance","amount"], comparator: "eq", threshold: 0, message: "{{count}} trial balance accounts with zero balance", description: "Accounts with zero balance should typically be omitted from the TB export to reduce noise.", detail: "{{count}} accounts have exactly zero balance.", impact: "Analysis noise — zero balance accounts add no value", recommendation: "Filter out zero-balance accounts from TB exports." },
  { id: "DI_040", layer: 1, name: "PL_ZERO_REVENUE", fileType: "profit_loss", category: "data_quality", severity: "high", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["revenue","turnover","sales"], mustExist: true, message: "Revenue accounts present but all show zero balance", description: "Revenue accounts with zero balance may indicate a missing income period or incorrect export.", detail: "Revenue account(s) found but with zero balance.", impact: "P&L completeness cannot be confirmed", recommendation: "Confirm the correct period has been exported and revenue is included.", evidenceStrength: "advisory" },

  // ── Integrity summary rules ────────────────────────────────────────────────
  { id: "DI_041", layer: 1, name: "AR_ZERO_BALANCE_ROWS", fileType: "aged_debtors", category: "data_quality", severity: "low", confidence: "high", type: "percentage", field: ["amount","balance"], keywords: ["0","0.00"], percentage: 30, message: "{{count}} AR rows have zero outstanding balance", description: "Aged debtor exports should typically only include rows with outstanding balances.", detail: "{{count}} rows ({{pct}}) in the aged debtors have zero balance.", impact: "Noise in the AR analysis", recommendation: "Filter zero-balance rows from aged debtors export." },
  { id: "DI_042", layer: 1, name: "AP_ZERO_BALANCE_ROWS", fileType: "aged_creditors", category: "data_quality", severity: "low", confidence: "high", type: "percentage", field: ["amount","balance"], keywords: ["0","0.00"], percentage: 30, message: "{{count}} AP rows have zero outstanding balance", description: "Aged creditor exports should include only rows with outstanding balances.", detail: "{{count}} rows ({{pct}}) in the aged creditors have zero balance.", impact: "Noise in the AP analysis", recommendation: "Filter zero-balance rows from aged creditors export." },
  { id: "DI_043", layer: 1, name: "TB_INTERCOMPANY_BALANCE", fileType: "trial_balance", category: "controls", severity: "high", confidence: "high", type: "existence", field: ["account_name"], keywords: ["intercompany","intra-group","due from group","due to group","related party"], mustExist: true, message: "Intercompany account balance requires disclosure and reconciliation", description: "Intercompany balances must be disclosed in the financial statements and reconciled with the counterpart entity.", detail: "{{count}} intercompany account(s) with outstanding balances: {{names}}", impact: "Disclosure and tax review required", recommendation: "Confirm intercompany balances with counterpart entities and ensure they are disclosed." },
  { id: "DI_044", layer: 1, name: "VAT_NEGATIVE_OUTPUT", fileType: "vat_report", category: "vat", severity: "medium", confidence: "high", type: "sign", field: ["vat_amount"], keywords: ["negative"], message: "Negative output VAT on {{count}} transactions", description: "Negative output VAT amounts on sales transactions may indicate credit note over-coding.", detail: "{{count}} transactions show negative output VAT.", impact: "VAT return calculation may be incorrect", recommendation: "Review transactions with negative output VAT — confirm credit notes are correctly coded." },
  { id: "DI_045", layer: 1, name: "AR_CREDIT_STATUS_ACCOUNTS", fileType: "aged_debtors", category: "ar", severity: "medium", confidence: "high", type: "keyword", field: ["status"], keywords: ["stop","stopped","on hold","credit hold","suspended","blocked"], message: "{{count}} customers on credit hold with outstanding balances", description: "Customers with credit stop or hold status should not have active outstanding invoices without management approval.", detail: "{{count}} credit-held accounts have outstanding balances.", impact: "Revenue and credit risk", recommendation: "Review credit-held accounts — confirm management approval for continued credit exposure." },
  { id: "DI_046", layer: 1, name: "TB_PAYROLL_TAX_MISSING", fileType: "trial_balance", category: "month_end", severity: "high", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["paye","payroll tax","national insurance","nic payable","tax payable"], mustExist: false, message: "No PAYE or payroll tax liability account found in the trial balance", description: "PAYE and National Insurance should appear as liabilities in the TB if payroll has been run.", detail: "No PAYE or NIC liability account detected.", impact: "Payroll may not have been posted", recommendation: "Confirm payroll journals have been posted including PAYE and NIC liabilities.", evidenceStrength: "indicator" },
  { id: "DI_047", layer: 1, name: "BS_MISSING_LIABILITIES", fileType: "balance_sheet", category: "data_quality", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["current liabilit","creditor","accrual","overdraft","tax liabilit"], mustExist: false, message: "No current liabilities found in the balance sheet", description: "A balance sheet without current liabilities may be missing creditors, accruals or overdraft.", detail: "No current liability rows detected.", impact: "Liquidity and creditor analysis not possible", recommendation: "Include current liabilities in the balance sheet export.", evidenceStrength: "advisory" },
  { id: "DI_048", layer: 1, name: "PL_MISSING_OPERATING_COSTS", fileType: "profit_loss", category: "data_quality", severity: "medium", confidence: "medium", type: "existence", field: ["account_name"], keywords: ["operating","overhead","admin","general","selling","distribution"], mustExist: false, message: "No operating overhead accounts found in the P&L", description: "A P&L without operating overhead rows may be missing key expense categories.", detail: "No overhead or operating cost accounts found.", impact: "Overhead analysis not possible", recommendation: "Include operating overhead accounts in the P&L export.", evidenceStrength: "advisory" },
  { id: "DI_049", layer: 1, name: "ANY_LARGE_ROUND_SINGLE", fileType: "any", category: "controls", severity: "low", confidence: "low", type: "threshold", field: ["amount","balance"], comparator: "gt", threshold: 100000, message: "{{count}} transactions exceed £100,000 and are round numbers", description: "Very large round-number transactions warrant manual review to confirm they represent genuine amounts.", detail: "{{count}} transactions exceed £100,000 and are exact round numbers.", impact: "Manual review recommended", recommendation: "Confirm large round-number transactions represent actual invoiced amounts." },
  { id: "DI_050", layer: 1, name: "TB_OPENING_BALANCE_MISSING", fileType: "trial_balance", category: "data_quality", severity: "low", confidence: "low", type: "existence", field: ["account_name"], keywords: ["opening balance","brought forward","b/f","opening"], mustExist: false, message: "No opening balance or brought-forward row found in the trial balance", description: "For period-specific reports, absence of opening balances means prior period comparatives cannot be assessed.", detail: "No opening balance or brought-forward rows detected.", impact: "Period comparison not possible", recommendation: "Include prior period opening balances in the TB export for comparison.", evidenceStrength: "advisory" },
];
