import type { AssuranceRule } from "@/lib/types/rule";

// Layer 4 — VAT Assurance Engine: 60 rules
// Purpose: Identify VAT compliance risk. Major UK differentiator.

const indicatorVatRules = new Set([
  "VAT_003", "VAT_007", "VAT_009", "VAT_010", "VAT_013", "VAT_014", "VAT_015", "VAT_016",
  "VAT_028", "VAT_030", "VAT_033", "VAT_035", "VAT_036", "VAT_037", "VAT_046",
]);

const rawVatAssuranceRules: AssuranceRule[] = [
  { id: "VAT_001", layer: 4, name: "BLANK_VAT_CODE", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "percentage", field: ["vat_code"], percentage: 1, message: "{{count}} transactions have no VAT code — return completeness risk", description: "Transactions without VAT codes cannot be correctly included in the VAT return.", detail: "{{count}} transactions ({{pct}}) are missing VAT/tax codes.", impact: "VAT return may be incomplete", recommendation: "Assign correct VAT codes to all transactions before submitting the VAT return." },
  { id: "VAT_002", layer: 4, name: "EXEMPT_ON_STANDARD_RATE_CATEGORY", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "keyword", field: ["vat_code"], keywords: ["exempt","E","ZR","zero","ES","EX","out of scope","OOS","N/A"], nameField: ["description","account_name"], message: "Exempt or zero-rate VAT code on standard-rate expense categories", description: "Services and supplies that should carry 20% standard rate VAT are coded as exempt or zero-rated.", detail: "{{count}} transactions coded exempt on standard-rate categories.", impact: "Under-claimed input VAT on VAT return", recommendation: "Correct VAT coding to standard rate (20%) for applicable transactions." },
  { id: "VAT_003", layer: 4, name: "REVERSE_CHARGE_MISSING", fileType: "vat_report", category: "vat", severity: "high", confidence: "medium", type: "keyword", field: ["description","supplier"], keywords: ["EU","European","overseas","import","non-UK","international","foreign"], nameField: ["supplier","description"], message: "{{count}} overseas supplier transactions — reverse charge VAT check required", description: "Services received from overseas suppliers may require reverse charge VAT accounting under UK rules.", detail: "{{count}} overseas supplier transactions where reverse charge may apply.", impact: "Potential VAT under-declaration", recommendation: "Review overseas supplier invoices — apply reverse charge accounting where applicable." },
  { id: "VAT_004", layer: 4, name: "INPUT_VAT_ON_ENTERTAINMENT", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "keyword", field: ["description"], keywords: ["entertainment","client entertainment","business entertainment","hospitality","golf","corporate event","staff party","christmas party","team event","team away"], nameField: ["description","supplier"], message: "{{count}} entertainment transactions with input VAT claimed — {{total}}", description: "HMRC blocks input VAT recovery on business entertainment — this VAT cannot be claimed.", detail: "{{count}} entertainment entries with input VAT: {{total}}", impact: "{{total}} non-reclaimable input VAT — remove from return", recommendation: "Remove input VAT on entertainment from the VAT return — HMRC will disallow it on inspection." },
  { id: "VAT_005", layer: 4, name: "FUEL_SCALE_CHARGE_MISSING", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description"], keywords: ["fuel","petrol","diesel","fuel card","mileage"], nameField: ["description","supplier"], message: "Fuel input VAT claimed — confirm fuel scale charge has been posted", description: "When reclaiming VAT on business fuel for company cars, a fuel scale charge must be posted to account for private use.", detail: "Fuel-related VAT entries detected but no fuel scale charge row found.", impact: "HMRC compliance risk if scale charge not posted", recommendation: "Post the fuel scale charge for the period — refer to HMRC fuel scale charge table.", evidenceStrength: "indicator" },
  { id: "VAT_006", layer: 4, name: "STAFF_SUBSISTENCE_VAT", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description"], keywords: ["subsistence","meal allowance","daily allowance","accommodation","hotel","B&B"], nameField: ["description","supplier"], message: "{{count}} staff subsistence transactions — VAT reclaim eligibility review", description: "VAT on staff subsistence is reclaimable only where expenses are wholly and exclusively for business and within HMRC guidelines.", detail: "{{count}} subsistence entries — confirm only business-purpose claims are included.", impact: "Non-business subsistence VAT is blocked", recommendation: "Review subsistence VAT claims — confirm only business-travel expenses are included and daily rates are within HMRC limits." },
  { id: "VAT_007", layer: 4, name: "PARTIAL_EXEMPTION_INDICATOR", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["vat_code"], keywords: ["partial","PE","exempt supply","mixed"], nameField: ["description","account_name"], message: "Partial exemption indicators detected — standard method calculation required", description: "If the business makes both taxable and exempt supplies, a partial exemption calculation is required.", detail: "{{count}} transactions indicate partial exemption activity.", impact: "Partial exemption standard method calculation required", recommendation: "Prepare partial exemption calculation using the standard method — apply annual adjustment if required." },
  { id: "VAT_008", layer: 4, name: "OUTPUT_VAT_ON_EXEMPT_SUPPLY", fileType: "vat_report", category: "vat", severity: "high", confidence: "medium", type: "keyword", field: ["description"], keywords: ["insurance","postage","financial service","health","medical","education","burial","lottery","bingo","funeral"], nameField: ["description","supplier"], message: "{{count}} output VAT charged on potentially exempt supplies", description: "Certain supplies are VAT exempt by statute — charging output VAT on these would be incorrect.", detail: "{{count}} transactions with output VAT on potentially exempt categories.", impact: "Output VAT may need to be reversed", recommendation: "Confirm VAT treatment of exempt supplies — reverse any incorrectly charged output VAT." },
  { id: "VAT_009", layer: 4, name: "CONSTRUCTION_REVERSE_CHARGE", fileType: "vat_report", category: "vat", severity: "high", confidence: "medium", type: "keyword", field: ["description","supplier"], keywords: ["construction","building","CIS","subcontract","brickwork","plumbing","electrical","roofing","scaffolding"], nameField: ["supplier","description"], message: "{{count}} construction services — domestic reverse charge VAT check", description: "From 1 March 2021, VAT on construction services between VAT-registered contractors/subcontractors uses domestic reverse charge.", detail: "{{count}} construction service transactions — review domestic reverse charge application.", impact: "Domestic reverse charge non-compliance risk", recommendation: "Confirm domestic reverse charge has been correctly applied on all construction subcontract services." },
  { id: "VAT_010", layer: 4, name: "DIGITAL_SERVICES_REVERSE_CHARGE", fileType: "vat_report", category: "vat", severity: "high", confidence: "medium", type: "keyword", field: ["description","supplier"], keywords: ["digital service","software subscription","SaaS","cloud service","online platform","streaming","app","Google","Microsoft","Adobe","Salesforce","AWS","Azure"], nameField: ["supplier","description"], message: "{{count}} digital service subscriptions — reverse charge VAT check", description: "Digital services from overseas providers (including EU tech companies) are subject to reverse charge.", detail: "{{count}} digital service transactions from overseas providers.", impact: "Reverse charge may be due on overseas digital services", recommendation: "Apply reverse charge accounting on all digital services from overseas providers not charging UK VAT." },
  { id: "VAT_011", layer: 4, name: "ZERO_RATE_EXPORTS_EVIDENCE", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["vat_code","description"], keywords: ["zero","Z","export","outside scope","goods exported"], nameField: ["description","supplier"], message: "{{count}} zero-rated supplies — confirm export evidence held", description: "Zero-rating for exports requires HMRC-specified documentary evidence to be held — without it, standard rate applies.", detail: "{{count}} zero-rated transactions — confirm export documentation.", impact: "HMRC may assess 20% on zero-rated exports if evidence is missing", recommendation: "Confirm export evidence (shipping documents, CMR, airway bills) is held for all zero-rated export sales." },
  { id: "VAT_012", layer: 4, name: "CARS_VAT_BLOCKED", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "keyword", field: ["description"], keywords: ["car purchase","motor car","new car","used car","second hand car","vehicle purchase","car lease"], nameField: ["description","supplier"], message: "{{count}} car purchase or lease transactions — VAT block check required", description: "Input VAT on cars available for private use is blocked (50% on leased cars; 100% blocked on purchased cars).", detail: "{{count}} car-related transactions detected.", impact: "Input VAT may be partially or fully blocked", recommendation: "Confirm VAT treatment on car purchases/leases — apply 50% block for leases; full block for purchased cars available for private use." },
  { id: "VAT_013", layer: 4, name: "SECOND_HAND_GOODS_MARGIN_SCHEME", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description"], keywords: ["second hand","secondhand","used goods","pre-owned","antique","vintage","margin scheme"], nameField: ["description","supplier"], message: "Second-hand goods detected — margin scheme VAT review", description: "Sales of second-hand goods may qualify for the VAT margin scheme — VAT is charged only on the profit margin.", detail: "{{count}} second-hand goods transactions identified.", impact: "Over-charging of output VAT if margin scheme not applied", recommendation: "Confirm whether the VAT margin scheme applies to second-hand goods sales." },
  { id: "VAT_014", layer: 4, name: "TOUR_OPERATORS_TOMS", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description","account_name"], keywords: ["tour operator","travel agent","holiday","package holiday","accommodation provider","TOMS"], nameField: ["description","supplier"], message: "Tour operator or travel transactions — TOMS review required", description: "Tour operators must use the Tour Operators Margin Scheme (TOMS) for calculating VAT on certain supplies.", detail: "{{count}} tour/travel transactions identified.", impact: "TOMS non-compliance risk", recommendation: "Confirm TOMS treatment is correctly applied for all tour operator supplies." },
  { id: "VAT_015", layer: 4, name: "CHARITIES_VAT_RELIEF", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description","supplier"], keywords: ["charity","charities","charitable","non-profit","not for profit","501c","relief"], nameField: ["description","supplier"], message: "{{count}} charity-related transactions — VAT relief eligibility review", description: "Qualifying charities may be eligible for VAT relief on certain goods and services.", detail: "{{count}} charity-related transactions identified.", impact: "VAT savings available if reliefs correctly claimed", recommendation: "Review charity VAT reliefs — submit retrospective claims where reliefs were not applied." },
  { id: "VAT_016", layer: 4, name: "LAND_AND_PROPERTY_VAT", fileType: "vat_report", category: "vat", severity: "high", confidence: "medium", type: "keyword", field: ["description"], keywords: ["land","property","option to tax","commercial property","real estate","freehold","leasehold"], nameField: ["description","supplier"], message: "Land or property transactions detected — VAT option to tax review", description: "Land and property is normally VAT exempt but may have a VAT option to tax — incorrect treatment has significant financial impact.", detail: "{{count}} land/property transactions identified.", impact: "Significant VAT risk if option to tax status is incorrect", recommendation: "Confirm VAT status and option to tax elections for all land and property transactions." },
  { id: "VAT_017", layer: 4, name: "VAT_REGISTRATION_THRESHOLD", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "threshold", field: ["net_amount","amount"], comparator: "gt", threshold: 85000, message: "Taxable supplies approaching or exceeding VAT registration threshold", description: "UK businesses must register for VAT when taxable turnover exceeds £85,000 in any 12-month period.", detail: "Cumulative taxable supplies detected — monitor against £85,000 threshold.", impact: "Compulsory VAT registration may be required", recommendation: "Monitor rolling 12-month taxable turnover — register for VAT before the threshold is breached.", evidenceStrength: "indicator" },
  { id: "VAT_018", layer: 4, name: "CASH_ACCOUNTING_ELIGIBLE", fileType: "vat_report", category: "vat", severity: "low", confidence: "low", type: "keyword", field: ["vat_code"], keywords: ["cash basis","cash accounting"], nameField: ["description"], message: "Cash accounting VAT indicator — confirm scheme eligibility", description: "Cash accounting for VAT is only available to businesses with taxable turnover below £1.35M.", detail: "{{count}} cash-basis VAT entries detected.", impact: "Confirm eligibility for cash accounting scheme", recommendation: "Confirm business is eligible for and correctly applying the cash accounting VAT scheme." },
  { id: "VAT_019", layer: 4, name: "INPUT_VAT_CORPORATE_HOSPITALITY", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "keyword", field: ["description"], keywords: ["corporate hospitality","corporate entertainment","client hospitality","sports hospitality","box","sponsorship event","dinner","lunch with client"], nameField: ["description","supplier"], message: "{{count}} corporate hospitality transactions with input VAT — likely blocked", description: "Corporate hospitality input VAT is blocked under HMRC rules — this cannot be reclaimed.", detail: "{{count}} corporate hospitality entries with VAT: {{total}}", impact: "{{total}} blocked input VAT — remove from return", recommendation: "Remove all corporate hospitality input VAT from the VAT return." },
  { id: "VAT_020", layer: 4, name: "EMPLOYEE_GIFTS_VAT", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description"], keywords: ["gift","employee gift","staff gift","christmas gift","birthday","leaving gift","voucher"], nameField: ["description","supplier"], message: "{{count}} employee gift transactions — VAT check required", description: "Business gifts to employees are exempt from output VAT only if total cost per employee per year is under £50.", detail: "{{count}} gift transactions identified.", impact: "Output VAT may be due on gifts exceeding the £50 threshold", recommendation: "Check if gifts to any employee exceed £50 per year — charge output VAT on excess amounts." },
  { id: "VAT_021", layer: 4, name: "BAD_DEBT_RELIEF_ELIGIBLE", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description","vat_code"], keywords: ["bad debt","written off","write off","irrecoverable"], nameField: ["description","supplier"], message: "Bad debt entries — VAT bad debt relief may be claimable", description: "VAT paid on invoices that become bad debts can be reclaimed where the debt is 6 months overdue.", detail: "{{count}} bad debt entries identified.", impact: "VAT bad debt relief may be due", recommendation: "Claim VAT bad debt relief for eligible invoices — ensure records are retained for HMRC." },
  { id: "VAT_022", layer: 4, name: "ACCOMMODATION_VAT_TREATMENT", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description"], keywords: ["hotel","accommodation","serviced apartment","Airbnb","B&B","hostel","guesthouse"], nameField: ["description","supplier"], message: "{{count}} accommodation transactions — VAT recovery check", description: "Staff accommodation for business purposes can have VAT recovered — but if mixed with personal use, recovery is restricted.", detail: "{{count}} accommodation transactions identified.", impact: "VAT recovery eligibility requires review", recommendation: "Confirm accommodation is for business purposes only — recover input VAT accordingly." },
  { id: "VAT_023", layer: 4, name: "SUPPLIES_TO_UNREGISTERED_PARTIES", fileType: "vat_report", category: "vat", severity: "low", confidence: "low", type: "keyword", field: ["vat_code"], keywords: ["unregistered","non-VAT registered","consumer","B2C","retail"], nameField: ["description"], message: "{{count}} supplies to unregistered parties — confirm retail VAT treatment", description: "Sales to unregistered businesses or consumers require standard VAT treatment — confirm rates are correct.", detail: "{{count}} transactions to unregistered parties identified.", impact: "Retail VAT treatment review required", recommendation: "Confirm VAT rates applied to sales to unregistered parties are correct." },
  { id: "VAT_024", layer: 4, name: "VAT_NOTICE_700_COMPLIANCE", fileType: "vat_report", category: "vat", severity: "low", confidence: "low", type: "keyword", field: ["vat_code"], keywords: ["T0","T1","T9","SR","ZR","RR","RI","RC","PVA"], nameField: ["description"], message: "{{count}} VAT codes used — confirm alignment with VAT Notice 700", description: "Ensure all VAT codes used align with HMRC guidance in VAT Notice 700.", detail: "{{count}} distinct VAT codes detected.", impact: "Non-standard codes may be misinterpreted by accounting software", recommendation: "Confirm all VAT codes used are HMRC-recognised and software-standard codes." },
  { id: "VAT_025", layer: 4, name: "POSTPONED_VAT_ACCOUNTING", fileType: "vat_report", category: "vat", severity: "high", confidence: "medium", type: "keyword", field: ["description","vat_code"], keywords: ["postponed VAT","PVA","import VAT","postponed accounting","MPIVS"], nameField: ["description","supplier"], message: "{{count}} import transactions — confirm postponed VAT accounting applied", description: "Post-Brexit, UK businesses importing goods can use Postponed VAT Accounting — this must be reflected correctly in the VAT return (boxes 1 and 4).", detail: "{{count}} import transactions detected.", impact: "Postponed VAT accounting may not be correctly reflected in the VAT return", recommendation: "Confirm PVA statement is downloaded from HMRC and correctly included in boxes 1 and 4 of the return." },
  { id: "VAT_026", layer: 4, name: "FLAT_RATE_SCHEME_CHECK", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["vat_code","description"], keywords: ["flat rate","FRS"], nameField: ["description"], message: "Flat Rate Scheme indicators detected — confirm FRS eligibility", description: "The VAT Flat Rate Scheme is available to businesses with turnover under £150,000 and offers simplicity.", detail: "Flat Rate Scheme indicators found in the VAT data.", impact: "Confirm FRS eligibility and rate applied", recommendation: "Confirm FRS turnover limit is not exceeded and the correct flat rate percentage is applied.", evidenceStrength: "advisory" },
  { id: "VAT_027", layer: 4, name: "ANNUAL_ACCOUNTING_SCHEME", fileType: "vat_report", category: "vat", severity: "low", confidence: "low", type: "keyword", field: ["vat_code","description"], keywords: ["annual accounting","annual return","single return"], nameField: ["description"], message: "Annual accounting indicators — confirm scheme compliance", description: "Annual Accounting Scheme users submit one return per year with interim payments — confirm payments are on schedule.", detail: "Annual accounting indicators detected.", impact: "Interim payment schedule compliance", recommendation: "Confirm annual accounting interim payments are on schedule and the balancing payment is correctly calculated.", evidenceStrength: "advisory" },
  { id: "VAT_028", layer: 4, name: "ZERO_RATED_FOOD_PRODUCTS", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description"], keywords: ["food","grocery","catering","bakery","restaurant","takeaway","confectionery"], nameField: ["description","supplier"], message: "{{count}} food/catering transactions — confirm VAT treatment", description: "Food VAT is complex — most food is zero-rated but hot food, catering and luxury items are standard-rated.", detail: "{{count}} food-related transactions identified.", impact: "Incorrect VAT rate risk on food supplies", recommendation: "Review food and catering VAT — apply standard rate to hot food, catering and luxury items; zero rate to cold food for home consumption." },
  { id: "VAT_029", layer: 4, name: "CHILDRENS_CLOTHING_ZERO_RATE", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description"], keywords: ["children","childrens","kids","infant","baby clothing","school uniform"], nameField: ["description","supplier"], message: "Children's clothing transactions — confirm zero-rating applied", description: "Children's clothing and footwear are zero-rated for VAT — standard rating these would be incorrect.", detail: "{{count}} children's clothing transactions identified.", impact: "Output VAT overcharge if standard-rated", recommendation: "Confirm zero-rate is applied to all children's clothing and footwear sales." },
  { id: "VAT_030", layer: 4, name: "SPORT_FACILITIES_EXEMPT", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description"], keywords: ["sports facility","sports hall","gym membership","swimming pool","leisure centre","fitness"], nameField: ["description","supplier"], message: "{{count}} sports/fitness transactions — VAT exemption review", description: "Certain sports services and facilities are VAT exempt when provided by non-profit bodies.", detail: "{{count}} sports/leisure transactions identified.", impact: "Incorrect output VAT if exemption not correctly applied", recommendation: "Confirm VAT treatment for sports and leisure facilities — exemption applies to non-profit eligible bodies." },
  { id: "VAT_031", layer: 4, name: "ELECTRONIC_PUBLICATIONS", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description"], keywords: ["ebook","digital book","digital publication","online newspaper","digital magazine","electronic book"], nameField: ["description","supplier"], message: "{{count}} digital publication transactions — zero-rate check", description: "From 1 May 2020, e-books and digital newspapers carry zero-rate VAT (same as physical books).", detail: "{{count}} digital publication transactions identified.", impact: "VAT over-charge if standard rated", recommendation: "Apply zero-rate VAT to e-books, digital newspapers and digital magazines from 1 May 2020." },
  { id: "VAT_032", layer: 4, name: "PROTECTIVE_EQUIPMENT_PPE_VAT", fileType: "vat_report", category: "vat", severity: "low", confidence: "low", type: "keyword", field: ["description"], keywords: ["PPE","protective equipment","safety equipment","hard hat","hi-vis","gloves","mask","face covering"], nameField: ["description","supplier"], message: "{{count}} PPE transactions — confirm VAT treatment", description: "Most PPE is standard-rated — confirm zero-rating has not been incorrectly applied.", detail: "{{count}} PPE/safety equipment transactions identified.", impact: "Incorrect zero-rating of standard-rated PPE", recommendation: "Confirm standard-rate VAT is applied to PPE purchases — zero-rating generally does not apply to PPE." },
  { id: "VAT_033", layer: 4, name: "MEDICAL_DEVICE_VAT", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description"], keywords: ["medical device","medical equipment","pharmaceutical","medicine","drug","prescription"], nameField: ["description","supplier"], message: "{{count}} medical transactions — VAT exemption or zero-rate check", description: "Medical devices, pharmaceutical supplies and some services may be VAT exempt or zero-rated.", detail: "{{count}} medical-related transactions identified.", impact: "VAT treatment for medical supplies is complex", recommendation: "Confirm VAT treatment for medical supplies — engage specialist VAT adviser if volumes are material." },
  { id: "VAT_034", layer: 4, name: "SPORTS_SPONSORSHIP_VAT", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description"], keywords: ["sponsorship","sponsor","shirt sponsor","naming rights","brand placement"], nameField: ["description","supplier"], message: "{{count}} sponsorship transactions — VAT treatment review", description: "Sponsorship VAT treatment depends on whether the sponsor receives a taxable supply in return — business sponsorship is usually standard-rated.", detail: "{{count}} sponsorship transactions identified.", impact: "Input VAT reclaim eligibility may be restricted", recommendation: "Confirm VAT treatment of sponsorship — business-to-business advertising is standard-rated; confirm input VAT entitlement." },
  { id: "VAT_035", layer: 4, name: "LOCAL_AUTHORITY_SUPPLIES", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description","supplier"], keywords: ["council","local authority","borough council","district council","county council"], nameField: ["description","supplier"], message: "{{count}} local authority transactions — section 33 VAT check", description: "Local authorities recover VAT under special Section 33 rules — supplies to/from local authorities have specific treatment.", detail: "{{count}} local authority-related transactions identified.", impact: "Section 33 VAT treatment may apply", recommendation: "Confirm correct VAT treatment for local authority transactions — specialist advice may be required." },
  { id: "VAT_036", layer: 4, name: "RESEARCH_VAT_EXEMPTION", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description"], keywords: ["research","R&D","research grant","academic research","scientific research"], nameField: ["description","supplier"], message: "{{count}} research-related transactions — VAT exemption check", description: "Research grants from government or charitable bodies may be outside the scope of VAT or qualify for exemption.", detail: "{{count}} research-related transactions identified.", impact: "Research grant VAT treatment may be out of scope", recommendation: "Confirm VAT treatment of research grants and contracts — specialist advice recommended for R&D-intensive businesses." },
  { id: "VAT_037", layer: 4, name: "PROPERTY_DEVELOPMENT_VAT", fileType: "vat_report", category: "vat", severity: "high", confidence: "medium", type: "keyword", field: ["description"], keywords: ["new build","property development","residential development","house build","zero-rated dwelling","first supply"], nameField: ["description","supplier"], message: "{{count}} property development transactions — zero-rate check for new builds", description: "The first supply of a new dwelling is zero-rated for VAT — subsequent supplies may be exempt or standard-rated.", detail: "{{count}} property development transactions identified.", impact: "Significant VAT recovery opportunity on new build projects", recommendation: "Confirm zero-rate application for first supply of new dwellings — seek specialist VAT advice." },
  { id: "VAT_038", layer: 4, name: "INVOICE_CREDIT_NOTE_MATCHING", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "sign", field: ["vat_amount"], keywords: ["negative"], nameField: ["description","supplier"], message: "{{count}} credit notes in VAT report — confirm matched to original invoices", description: "VAT credit notes must be matched to the original invoice and correctly reflected in the period of issue.", detail: "{{count}} negative VAT amounts (credit notes) in the VAT report.", impact: "Incorrect period inclusion of credit note VAT", recommendation: "Confirm all credit notes are correctly matched to original invoices and included in the correct VAT period." },
  { id: "VAT_039", layer: 4, name: "INTRASTAT_THRESHOLD_CHECK", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description","supplier"], keywords: ["EU","European Union","Northern Ireland","intrastat","arrival","dispatch"], nameField: ["description","supplier"], message: "{{count}} EU transactions — Intrastat threshold monitoring", description: "UK businesses trading goods with EU must submit Intrastat declarations if arrivals/dispatches exceed £500,000.", detail: "{{count}} EU-related transactions identified.", impact: "Intrastat reporting obligations may apply", recommendation: "Monitor EU goods trade volumes — submit Intrastat arrivals/dispatches declarations if thresholds are exceeded." },
  { id: "VAT_040", layer: 4, name: "VAT_INVOICE_REQUIREMENTS", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "percentage", field: ["vat_code","net_amount"], keywords: [], percentage: 5, message: "{{count}} large VAT transactions without full invoice details", description: "VAT invoices must include supplier VAT registration number, unique invoice number, supply date and tax point.", detail: "{{count}} transactions may lack sufficient invoice details for VAT recovery.", impact: "Input VAT may be disallowed without valid VAT invoices", recommendation: "Ensure all input VAT claims are supported by valid VAT invoices meeting HMRC requirements." },
  { id: "VAT_041", layer: 4, name: "ANNUAL_ADJUSTMENT_REMINDER", fileType: "vat_report", category: "vat", severity: "low", confidence: "low", type: "keyword", field: ["vat_code","description"], keywords: ["annual adjustment","capital goods scheme","CGS","annual test"], nameField: ["description"], message: "Annual VAT adjustment may be required", description: "Partial exemption businesses must perform an annual adjustment test at the end of their VAT year.", detail: "Annual VAT adjustment indicators detected.", impact: "Annual partial exemption adjustment required", recommendation: "Complete the annual partial exemption test and post any required adjustment in the appropriate VAT period.", evidenceStrength: "advisory" },
  { id: "VAT_042", layer: 4, name: "CAPITAL_GOODS_SCHEME", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description"], keywords: ["capital goods scheme","CGS","computer","aircraft","boat","land purchase","building purchase"], nameField: ["description","supplier"], message: "{{count}} capital goods scheme assets detected", description: "The Capital Goods Scheme requires VAT adjustments over 5 years (computers) or 10 years (land and buildings) where usage changes.", detail: "{{count}} capital goods scheme items identified.", impact: "CGS annual adjustments may be required", recommendation: "Register qualifying assets in the CGS — perform annual adjustments to reflect changes in taxable use." },
  { id: "VAT_043", layer: 4, name: "TOURIST_REFUND_SCHEME", fileType: "vat_report", category: "vat", severity: "low", confidence: "low", type: "keyword", field: ["description"], keywords: ["VAT refund","tourist refund","retail export","tax free shopping","visitor refund"], nameField: ["description"], message: "Tourist or visitor VAT refund transactions detected", description: "Overseas visitors buying goods for export from the UK may claim VAT refunds — this affects output VAT.", detail: "{{count}} tourist refund transactions identified.", impact: "Output VAT adjustments required for visitor refund scheme", recommendation: "Confirm correct processing of tourist refund scheme transactions in the VAT return." },
  { id: "VAT_044", layer: 4, name: "CHARITY_ZERO_RATE_GOODS", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description","vat_code"], keywords: ["charity zero rate","eligible goods for charity","charity relief"], nameField: ["description","supplier"], message: "{{count}} zero-rated charity goods — confirm eligible relief", description: "Certain goods supplied to charities qualify for zero-rate VAT relief — confirm eligibility certificates are held.", detail: "{{count}} charity zero-rate transactions identified.", impact: "Zero-rate relief may require eligibility documentation", recommendation: "Obtain and retain charity eligibility certificates for all zero-rated charity supplies." },
  { id: "VAT_045", layer: 4, name: "LEASE_VAT_TREATMENT", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "keyword", field: ["description"], keywords: ["lease","hire","rental","asset hire","equipment lease","finance lease","operating lease"], nameField: ["description","supplier"], message: "{{count}} lease/rental transactions — VAT treatment review", description: "VAT on leased assets depends on asset type and lease structure — cars and certain assets have specific rules.", detail: "{{count}} lease/rental transactions identified.", impact: "50% VAT block may apply to leased cars", recommendation: "Review VAT treatment of each lease — apply 50% block to car leases; recover full VAT on commercial vehicles." },
  { id: "VAT_046", layer: 4, name: "DISTANCE_SELLING_VAT", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description","supplier"], keywords: ["distance selling","online sale","ecommerce","marketplace","Etsy","eBay","Amazon seller"], nameField: ["description"], message: "{{count}} distance selling transactions — EU OSS check", description: "Post-Brexit UK businesses selling goods to EU consumers may need to register for EU One Stop Shop (OSS).", detail: "{{count}} potential distance selling transactions identified.", impact: "EU VAT registration and OSS obligations may arise", recommendation: "Monitor distance sales to EU consumers — register for OSS if annual EU sales exceed local thresholds." },
  { id: "VAT_047", layer: 4, name: "PROMPT_PAYMENT_DISCOUNT_VAT", fileType: "vat_report", category: "vat", severity: "low", confidence: "low", type: "keyword", field: ["description","vat_code"], keywords: ["prompt payment","settlement discount","early payment","PPD","SPD"], nameField: ["description"], message: "{{count}} prompt payment discount transactions — VAT treatment check", description: "Since September 2014, VAT on prompt payment discounts must be calculated on the full invoice amount, not the discounted amount.", detail: "{{count}} PPD/SPD transactions identified.", impact: "Incorrect VAT if PPD VAT rules not correctly applied", recommendation: "Confirm VAT is calculated on the full invoice amount for all prompt payment discount transactions." },
  { id: "VAT_048", layer: 4, name: "REVERSE_CHARGE_BOX_1_ADJUSTMENT", fileType: "vat_report", category: "vat", severity: "high", confidence: "medium", type: "keyword", field: ["vat_code","description"], keywords: ["reverse charge","RC","RCSL","RCSS","acquisition tax","import VAT PVA"], nameField: ["description","supplier"], message: "{{count}} reverse charge transactions — confirm Box 1 and Box 4 are both populated", description: "Reverse charge VAT must be declared in both Box 1 (output) and Box 4 (input) of the VAT return.", detail: "{{count}} reverse charge transactions identified — confirm dual-box treatment.", impact: "Missing Box 1 entry creates under-declaration risk", recommendation: "Confirm all reverse charge transactions appear in both Box 1 and Box 4 of the VAT return." },
  { id: "VAT_049", layer: 4, name: "SELF_BILLING_ARRANGEMENTS", fileType: "vat_report", category: "vat", severity: "low", confidence: "low", type: "keyword", field: ["description","vat_code"], keywords: ["self-billing","self billing","SBI","self-issued invoice"], nameField: ["description","supplier"], message: "{{count}} self-billing arrangement transactions — agreement required", description: "Self-billing can only be used where a formal self-billing agreement exists between the parties.", detail: "{{count}} self-billing transactions identified.", impact: "Self-billing without agreement is invalid", recommendation: "Confirm valid self-billing agreements exist for all self-issued invoices." },
  { id: "VAT_050", layer: 4, name: "VAT_GROUP_REGISTRATION", fileType: "vat_report", category: "vat", severity: "medium", confidence: "low", type: "keyword", field: ["description","supplier"], keywords: ["group VAT","VAT group","group registration","representative member"], nameField: ["description"], message: "VAT group indicators detected — confirm representative member", description: "VAT group registrations require a representative member responsible for the group VAT return.", detail: "VAT group indicators found in the data.", impact: "Group VAT compliance requires representative member oversight", recommendation: "Confirm the VAT group structure, representative member and that all supplies within the group are excluded from the return.", evidenceStrength: "advisory" },

  // ── Missing VAT rules identified in review ──────────────────────────────────

  // VAT-vs-control is reconciled by REC_003 (reconciliation-engine) on a NET
  // basis. This threshold rule summed VAT gross (both output and input) and fired
  // on any VAT at all, contradicting REC_003's net result — so it was retired.

  { id: "VAT_052", layer: 4, name: "VAT_BOX_1_OUTPUT_COMPLETENESS", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "existence", field: ["vat_code"], keywords: ["S","T1","SR","STD","20%","standard"], mustExist: true, nameField: ["description"], message: "Standard-rated output VAT present — confirm Box 1 amount is complete", description: "Box 1 of the VAT return must include all standard-rated output tax for the period. Verify the VAT report total agrees to Box 1.", detail: "Standard-rated output VAT transactions detected — confirm Box 1 completeness.", impact: "Under-declaration in Box 1 creates HMRC assessment risk", recommendation: "Reconcile all output VAT to Box 1 of the VAT return — ensure no standard-rated sales are omitted.", evidenceStrength: "deterministic" },

  { id: "VAT_053", layer: 4, name: "VAT_EFFECTIVE_RATE_PURCHASE", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "variance", field: ["vat_amount"], percentage: 30, message: "Input VAT effective rate shows high variance — possible mis-coding", description: "The ratio of input VAT to net purchases (effective input VAT rate) should be broadly consistent. High variance suggests incorrect VAT coding on purchases.", detail: "Input VAT amounts show high statistical variance relative to net values.", impact: "Mis-coded input VAT rates affect reclaim accuracy", recommendation: "Calculate effective input VAT rate (VAT ÷ Net × 100) — investigate transactions where rate deviates significantly from 20%, 5% or 0%.", evidenceStrength: "indicator" },

  { id: "VAT_054", layer: 4, name: "VAT_EFFECTIVE_RATE_SALES", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "variance", field: ["vat_amount"], percentage: 30, message: "Output VAT effective rate shows high variance — review coding", description: "The ratio of output VAT to net sales (effective output VAT rate) should be broadly stable period-to-period. High variance suggests a mix of rates that needs review.", detail: "Output VAT amounts show high statistical variance.", impact: "Output VAT rate anomalies create HMRC query risk", recommendation: "Calculate effective output VAT rate — compare to prior period. Investigate if the mix of standard/reduced/zero-rated sales has changed materially.", evidenceStrength: "indicator" },

  { id: "VAT_055", layer: 4, name: "VAT_BOX_4_INPUT_COMPLETENESS", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "existence", field: ["vat_code"], keywords: ["P","PUR","INPUT","INPUT VAT","T1","SR","STD","20%"], mustExist: true, nameField: ["description","supplier"], message: "Input VAT detected — confirm Box 4 amount is complete", description: "Box 4 must include all recoverable input VAT for the period.", detail: "Input VAT transactions detected — reconcile recoverable input VAT to Box 4.", impact: "Input VAT under/over claim risk", recommendation: "Reconcile recoverable input VAT to Box 4 before submission.", evidenceStrength: "deterministic" },

  { id: "VAT_056", layer: 4, name: "VAT_BOX_6_OUTPUT_RECONCILIATION", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "threshold", field: ["net_amount","amount","gross_ex_vat"], comparator: "gt", threshold: 0, nameField: ["description","customer"], message: "Taxable sales detected — reconcile to Box 6", description: "Box 6 should agree to taxable outputs excluding VAT.", detail: "Positive taxable sales values detected in the VAT report.", impact: "VAT return sales misstatement", recommendation: "Reconcile taxable sales to Box 6 and investigate any difference before submission.", evidenceStrength: "deterministic" },

  { id: "VAT_057", layer: 4, name: "VAT_BOX_7_PURCHASE_RECONCILIATION", fileType: "vat_report", category: "vat", severity: "high", confidence: "high", type: "threshold", field: ["net_amount","amount","gross_ex_vat"], comparator: "gt", threshold: 0, nameField: ["description","supplier"], message: "Taxable purchases detected — reconcile to Box 7", description: "Box 7 should agree to taxable purchases excluding VAT.", detail: "Positive taxable purchase values detected in the VAT report.", impact: "VAT return purchase misstatement", recommendation: "Reconcile taxable purchases to Box 7 and investigate any difference before submission.", evidenceStrength: "deterministic" },

  { id: "VAT_058", layer: 4, name: "VAT_PRIOR_PERIOD_VARIANCE", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "variance", field: ["vat_amount","tax_amount","vat","tax"], percentage: 50, message: "VAT movement materially different from prior period", description: "Large changes in VAT profile may indicate coding errors or genuine business changes requiring explanation.", detail: "Current period VAT differs materially from expected trend.", impact: "Potential VAT anomaly", recommendation: "Review VAT trends against prior periods and document the reason for material movements.", evidenceStrength: "indicator" },

  { id: "VAT_059", layer: 4, name: "VAT_EFFECTIVE_RATE_PERIOD_COMPARISON", fileType: "vat_report", category: "vat", severity: "medium", confidence: "medium", type: "variance", field: ["vat_amount","tax_amount","vat","tax"], percentage: 20, message: "Effective VAT rate differs significantly from prior period", description: "Unexpected VAT rate movements may indicate coding issues or a change in the mix of standard, reduced, zero-rated and exempt supplies.", detail: "Effective VAT rate differs from historical average.", impact: "Potential VAT coding inconsistency", recommendation: "Review standard, reduced, zero-rated and exempt transactions and explain any rate movement.", evidenceStrength: "indicator" },

  { id: "VAT_060", layer: 4, name: "VAT_RETURN_READINESS_SCORE", fileType: "vat_report", category: "vat", severity: "low", confidence: "high", type: "existence", field: ["vat_code"], keywords: ["S","T1","SR","STD","20%","P","PUR","INPUT","RC","reverse charge","PVA"], mustExist: true, message: "Generate VAT readiness score", description: "Calculate VAT readiness based on VAT assurance, box validation, coding completeness and reconciliation outcomes.", detail: "VAT readiness assessment generated from uploaded VAT report indicators.", impact: "Provides filing confidence assessment", recommendation: "Resolve all high-severity VAT findings before submission.", evidenceStrength: "advisory" },
];

export const vatAssuranceRules: AssuranceRule[] = rawVatAssuranceRules.map((rule) =>
  indicatorVatRules.has(rule.id)
    ? { ...rule, evidenceStrength: "indicator" as const }
    : rule
);
